//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.App_Lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GB.App_Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abbreviation.
        /// </summary>
        public static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activate edit.
        /// </summary>
        public static string Activate_edit {
            get {
                return ResourceManager.GetString("Activate_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activated.
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string Add_ {
            get {
                return ResourceManager.GetString("Add_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Agence management.
        /// </summary>
        public static string Agence_management {
            get {
                return ResourceManager.GetString("Agence_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Agency.
        /// </summary>
        public static string Agency {
            get {
                return ResourceManager.GetString("Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount max.
        /// </summary>
        public static string Amount_max {
            get {
                return ResourceManager.GetString("Amount_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount min.
        /// </summary>
        public static string Amount_min {
            get {
                return ResourceManager.GetString("Amount_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ANNUALY.
        /// </summary>
        public static string Annualy {
            get {
                return ResourceManager.GetString("Annualy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application language.
        /// </summary>
        public static string Application_language {
            get {
                return ResourceManager.GetString("Application_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect account or password.
        /// </summary>
        public static string Authentication_failed_1 {
            get {
                return ResourceManager.GetString("Authentication_failed_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This account is suspended.
        /// </summary>
        public static string Authentication_failed_2 {
            get {
                return ResourceManager.GetString("Authentication_failed_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The password has expired.
        /// </summary>
        public static string Authentication_failed_3 {
            get {
                return ResourceManager.GetString("Authentication_failed_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You do not have permissions in the system.
        /// </summary>
        public static string Authentication_failed_4 {
            get {
                return ResourceManager.GetString("Authentication_failed_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup method.
        /// </summary>
        public static string Backup_method {
            get {
                return ResourceManager.GetString("Backup_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bank holiday management.
        /// </summary>
        public static string Bank_holiday_management {
            get {
                return ResourceManager.GetString("Bank_holiday_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BEAC nationality management.
        /// </summary>
        public static string BEAC_nationality_management {
            get {
                return ResourceManager.GetString("BEAC_nationality_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Branch manager.
        /// </summary>
        public static string Branch_manager {
            get {
                return ResourceManager.GetString("Branch_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Budget directionate management.
        /// </summary>
        public static string Budget_directionate_management {
            get {
                return ResourceManager.GetString("Budget_directionate_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm action.
        /// </summary>
        public static string Confirm_action {
            get {
                return ResourceManager.GetString("Confirm_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection status.
        /// </summary>
        public static string Connection_status {
            get {
                return ResourceManager.GetString("Connection_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Control number of loans.
        /// </summary>
        public static string Control_number_of_loans {
            get {
                return ResourceManager.GetString("Control_number_of_loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Control session.
        /// </summary>
        public static string Control_session {
            get {
                return ResourceManager.GetString("Control_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accept and continue.
        /// </summary>
        public static string Cookie_button {
            get {
                return ResourceManager.GetString("Cookie_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In order to offer you the best experience, our application uses cookies. By continuing to use this application, you agree to our use of cookies..
        /// </summary>
        public static string Cookie_message {
            get {
                return ResourceManager.GetString("Cookie_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à © 2018 All rights reserved &lt;b&gt;Better Planning Ltd&lt;/b&gt;.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Count account.
        /// </summary>
        public static string Count_account {
            get {
                return ResourceManager.GetString("Count_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Count page number statement.
        /// </summary>
        public static string Count_page_number_statement {
            get {
                return ResourceManager.GetString("Count_page_number_statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Countrie.
        /// </summary>
        public static string Countrie {
            get {
                return ResourceManager.GetString("Countrie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation date.
        /// </summary>
        public static string Creation_date {
            get {
                return ResourceManager.GetString("Creation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current currency.
        /// </summary>
        public static string Current_currency {
            get {
                return ResourceManager.GetString("Current_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customer max credit.
        /// </summary>
        public static string Customer_max_credit {
            get {
                return ResourceManager.GetString("Customer_max_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customer max debit.
        /// </summary>
        public static string Customer_max_debit {
            get {
                return ResourceManager.GetString("Customer_max_debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customer overdraft limit.
        /// </summary>
        public static string Customer_overdraft_limit {
            get {
                return ResourceManager.GetString("Customer_overdraft_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Del.
        /// </summary>
        public static string Del_ {
            get {
                return ResourceManager.GetString("Del_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete menus.
        /// </summary>
        public static string Delete_menus {
            get {
                return ResourceManager.GetString("Delete_menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Devise management.
        /// </summary>
        public static string Devise_management {
            get {
                return ResourceManager.GetString("Devise_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        public static string Differential {
            get {
                return ResourceManager.GetString("Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directionate head.
        /// </summary>
        public static string Directionate_head {
            get {
                return ResourceManager.GetString("Directionate_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dormant period.
        /// </summary>
        public static string Dormant_period {
            get {
                return ResourceManager.GetString("Dormant_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Economic activities management.
        /// </summary>
        public static string Economic_activities_management {
            get {
                return ResourceManager.GetString("Economic_activities_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee historical access.
        /// </summary>
        public static string Employee_historical_access {
            get {
                return ResourceManager.GetString("Employee_historical_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ending date.
        /// </summary>
        public static string Ending_date {
            get {
                return ResourceManager.GetString("Ending_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erasing.
        /// </summary>
        public static string Erasing {
            get {
                return ResourceManager.GetString("Erasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while processing, please contact the administrator..
        /// </summary>
        public static string Error_message_notification {
            get {
                return ResourceManager.GetString("Error_message_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A communication error has occurred.
        /// </summary>
        public static string Error_server_message {
            get {
                return ResourceManager.GetString("Error_server_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Existing data.
        /// </summary>
        public static string Existing_data {
            get {
                return ResourceManager.GetString("Existing_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Existing day.
        /// </summary>
        public static string Existing_day {
            get {
                return ResourceManager.GetString("Existing_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expiration duration.
        /// </summary>
        public static string Expiration_duration {
            get {
                return ResourceManager.GetString("Expiration_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fiscals exercice management.
        /// </summary>
        public static string Fiscals_exercice_management {
            get {
                return ResourceManager.GetString("Fiscals_exercice_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Garantie deposit.
        /// </summary>
        public static string Garantie_deposit {
            get {
                return ResourceManager.GetString("Garantie_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General banking parameters.
        /// </summary>
        public static string General_banking_parameters {
            get {
                return ResourceManager.GetString("General_banking_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General parameters.
        /// </summary>
        public static string General_parameters {
            get {
                return ResourceManager.GetString("General_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Institution management.
        /// </summary>
        public static string Institution_management {
            get {
                return ResourceManager.GetString("Institution_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Institutional unit management.
        /// </summary>
        public static string Institutional_unit_management {
            get {
                return ResourceManager.GetString("Institutional_unit_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internal error.
        /// </summary>
        public static string Internal_error {
            get {
                return ResourceManager.GetString("Internal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid date.
        /// </summary>
        public static string Invalid_date {
            get {
                return ResourceManager.GetString("Invalid_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IP Address.
        /// </summary>
        public static string IP_Address {
            get {
                return ResourceManager.GetString("IP_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Judicial products management.
        /// </summary>
        public static string Judicial_products_management {
            get {
                return ResourceManager.GetString("Judicial_products_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last transaction.
        /// </summary>
        public static string Last_transaction {
            get {
                return ResourceManager.GetString("Last_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Line of credit max amount.
        /// </summary>
        public static string Line_of_credit_max_amount {
            get {
                return ResourceManager.GetString("Line_of_credit_max_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of records.
        /// </summary>
        public static string List_of_records {
            get {
                return ResourceManager.GetString("List_of_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Listing.
        /// </summary>
        public static string Listing {
            get {
                return ResourceManager.GetString("Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Litigation.
        /// </summary>
        public static string Litigation {
            get {
                return ResourceManager.GetString("Litigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Litigation period.
        /// </summary>
        public static string Litigation_period {
            get {
                return ResourceManager.GetString("Litigation_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loan.
        /// </summary>
        public static string Loan {
            get {
                return ResourceManager.GetString("Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loan limit amount.
        /// </summary>
        public static string Loan_limit_amount {
            get {
                return ResourceManager.GetString("Loan_limit_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login to the application.
        /// </summary>
        public static string Login_application {
            get {
                return ResourceManager.GetString("Login_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lst.
        /// </summary>
        public static string Lst_ {
            get {
                return ResourceManager.GetString("Lst_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Management of banking parameters.
        /// </summary>
        public static string Management_of_banking_parameters {
            get {
                return ResourceManager.GetString("Management_of_banking_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu group.
        /// </summary>
        public static string Menu_group {
            get {
                return ResourceManager.GetString("Menu_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu management.
        /// </summary>
        public static string Menu_Management {
            get {
                return ResourceManager.GetString("Menu_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mod.
        /// </summary>
        public static string Mod_ {
            get {
                return ResourceManager.GetString("Mod_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify custom attributes in branch.
        /// </summary>
        public static string Modify_custom_attributes_in_branch {
            get {
                return ResourceManager.GetString("Modify_custom_attributes_in_branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module management.
        /// </summary>
        public static string Module_Management {
            get {
                return ResourceManager.GetString("Module_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MONTHLY.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Necessary privilege load action.
        /// </summary>
        public static string Necessary_privilege_loading_action {
            get {
                return ResourceManager.GetString("Necessary_privilege_loading_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New menus.
        /// </summary>
        public static string New_menus {
            get {
                return ResourceManager.GetString("New_menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Night run posting options.
        /// </summary>
        public static string Night_run_posting_options {
            get {
                return ResourceManager.GetString("Night_run_posting_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No changes have been made.
        /// </summary>
        public static string No_changes_have_been_made {
            get {
                return ResourceManager.GetString("No_changes_have_been_made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No item selected.
        /// </summary>
        public static string No_item_selected {
            get {
                return ResourceManager.GetString("No_item_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No payment period.
        /// </summary>
        public static string No_payment_period {
            get {
                return ResourceManager.GetString("No_payment_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number day before write off.
        /// </summary>
        public static string Number_day_before_write_off {
            get {
                return ResourceManager.GetString("Number_day_before_write_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object not found.
        /// </summary>
        public static string Object_not_found {
            get {
                return ResourceManager.GetString("Object_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open back date.
        /// </summary>
        public static string Open_back_date {
            get {
                return ResourceManager.GetString("Open_back_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open back working date.
        /// </summary>
        public static string Open_back_working_date {
            get {
                return ResourceManager.GetString("Open_back_working_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open branch.
        /// </summary>
        public static string Open_branch {
            get {
                return ResourceManager.GetString("Open_branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page not found.
        /// </summary>
        public static string Page_not_found {
            get {
                return ResourceManager.GetString("Page_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à THE PAGE YOU TRY TO ACCESS IS NOT AVAILABLE.
        /// </summary>
        public static string Page_not_found_message {
            get {
                return ResourceManager.GetString("Page_not_found_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password expiration.
        /// </summary>
        public static string Password_expiration {
            get {
                return ResourceManager.GetString("Password_expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path first backup.
        /// </summary>
        public static string Path_first_backup {
            get {
                return ResourceManager.GetString("Path_first_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path last backup.
        /// </summary>
        public static string Path_last_backup {
            get {
                return ResourceManager.GetString("Path_last_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pays management.
        /// </summary>
        public static string Pays_management {
            get {
                return ResourceManager.GetString("Pays_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Periodicity.
        /// </summary>
        public static string Periodicity {
            get {
                return ResourceManager.GetString("Periodicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Permission denied.
        /// </summary>
        public static string Permission_denied {
            get {
                return ResourceManager.GetString("Permission_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Permission to list records denied.
        /// </summary>
        public static string Permission_to_list_records_denied {
            get {
                return ResourceManager.GetString("Permission_to_list_records_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone id.
        /// </summary>
        public static string Phone_id {
            get {
                return ResourceManager.GetString("Phone_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Physical products management.
        /// </summary>
        public static string Physical_products_management {
            get {
                return ResourceManager.GetString("Physical_products_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Post loan litigation.
        /// </summary>
        public static string Post_loan_litigation {
            get {
                return ResourceManager.GetString("Post_loan_litigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Post local collection.
        /// </summary>
        public static string Post_local_collection {
            get {
                return ResourceManager.GetString("Post_local_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Post term and time deposits.
        /// </summary>
        public static string Post_term_and_time_deposits {
            get {
                return ResourceManager.GetString("Post_term_and_time_deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à P.O. Box.
        /// </summary>
        public static string Postal_code {
            get {
                return ResourceManager.GetString("Postal_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Privilege management.
        /// </summary>
        public static string Privilege_management {
            get {
                return ResourceManager.GetString("Privilege_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process in production.
        /// </summary>
        public static string Process_in_production {
            get {
                return ResourceManager.GetString("Process_in_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Product information.
        /// </summary>
        public static string Product_information {
            get {
                return ResourceManager.GetString("Product_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prt.
        /// </summary>
        public static string Prt_ {
            get {
                return ResourceManager.GetString("Prt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à QUATERLY.
        /// </summary>
        public static string Quaterly {
            get {
                return ResourceManager.GetString("Quaterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reconnect.
        /// </summary>
        public static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ReportName management.
        /// </summary>
        public static string ReportName_management {
            get {
                return ResourceManager.GetString("ReportName_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reserve interest.
        /// </summary>
        public static string Reserve_interest {
            get {
                return ResourceManager.GetString("Reserve_interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reserve interest post method.
        /// </summary>
        public static string Reserve_interest_post_method {
            get {
                return ResourceManager.GetString("Reserve_interest_post_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Role and privilege management.
        /// </summary>
        public static string Role_and_privilege_management {
            get {
                return ResourceManager.GetString("Role_and_privilege_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rule management.
        /// </summary>
        public static string Rule_Management {
            get {
                return ResourceManager.GetString("Rule_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rules.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search a role.
        /// </summary>
        public static string Search_a_role {
            get {
                return ResourceManager.GetString("Search_a_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search by.
        /// </summary>
        public static string Search_by {
            get {
                return ResourceManager.GetString("Search_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SEMESTER.
        /// </summary>
        public static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Session duration.
        /// </summary>
        public static string Session_duration {
            get {
                return ResourceManager.GetString("Session_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign.
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign Out.
        /// </summary>
        public static string Sign_Out {
            get {
                return ResourceManager.GetString("Sign_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signing amount.
        /// </summary>
        public static string Signing_amount {
            get {
                return ResourceManager.GetString("Signing_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signing authority management.
        /// </summary>
        public static string Signing_authority_management {
            get {
                return ResourceManager.GetString("Signing_authority_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SMS banking.
        /// </summary>
        public static string SMS_banking {
            get {
                return ResourceManager.GetString("SMS_banking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting date.
        /// </summary>
        public static string Starting_date {
            get {
                return ResourceManager.GetString("Starting_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statement page count.
        /// </summary>
        public static string Statement_page_count {
            get {
                return ResourceManager.GetString("Statement_page_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successful.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suspended.
        /// </summary>
        public static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file must not exceed.
        /// </summary>
        public static string The_file_must_not_exceed {
            get {
                return ResourceManager.GetString("The_file_must_not_exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The object must have a unique id.
        /// </summary>
        public static string The_object_must_have_a_unique_id {
            get {
                return ResourceManager.GetString("The_object_must_have_a_unique_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This account is suspended.
        /// </summary>
        public static string This_account_is_suspended {
            get {
                return ResourceManager.GetString("This_account_is_suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This day not exist.
        /// </summary>
        public static string This_day_not_exist {
            get {
                return ResourceManager.GetString("This_day_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This product will be apply to the following transactions.
        /// </summary>
        public static string This_product_will_be_apply_to_the_following_transactions {
            get {
                return ResourceManager.GetString("This_product_will_be_apply_to_the_following_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time deposit.
        /// </summary>
        public static string Time_deposit {
            get {
                return ResourceManager.GetString("Time_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title management.
        /// </summary>
        public static string Title_management {
            get {
                return ResourceManager.GetString("Title_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To log in.
        /// </summary>
        public static string To_log_in {
            get {
                return ResourceManager.GetString("To_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Town.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Town management.
        /// </summary>
        public static string Town_management {
            get {
                return ResourceManager.GetString("Town_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unpaid.
        /// </summary>
        public static string Unpaid {
            get {
                return ResourceManager.GetString("Unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update customer position.
        /// </summary>
        public static string Update_customer_position {
            get {
                return ResourceManager.GetString("Update_customer_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use central version.
        /// </summary>
        public static string Use_central_version {
            get {
                return ResourceManager.GetString("Use_central_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use check booklet.
        /// </summary>
        public static string Use_check_booklet {
            get {
                return ResourceManager.GetString("Use_check_booklet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use cobac litigation method.
        /// </summary>
        public static string Use_cobac_litigation_method {
            get {
                return ResourceManager.GetString("Use_cobac_litigation_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User management.
        /// </summary>
        public static string User_Management {
            get {
                return ResourceManager.GetString("User_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à V.A.T..
        /// </summary>
        public static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Views.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
