//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.App_Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GB.App_Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation.
        /// </summary>
        public static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate edit.
        /// </summary>
        public static string Activate_edit {
            get {
                return ResourceManager.GetString("Activate_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add_ {
            get {
                return ResourceManager.GetString("Add_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agence management.
        /// </summary>
        public static string Agence_management {
            get {
                return ResourceManager.GetString("Agence_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency.
        /// </summary>
        public static string Agency {
            get {
                return ResourceManager.GetString("Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount max.
        /// </summary>
        public static string Amount_max {
            get {
                return ResourceManager.GetString("Amount_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount min.
        /// </summary>
        public static string Amount_min {
            get {
                return ResourceManager.GetString("Amount_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application language.
        /// </summary>
        public static string Application_language {
            get {
                return ResourceManager.GetString("Application_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset location management.
        /// </summary>
        public static string Asset_location_management {
            get {
                return ResourceManager.GetString("Asset_location_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets type management.
        /// </summary>
        public static string Assets_type_management {
            get {
                return ResourceManager.GetString("Assets_type_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect account or password.
        /// </summary>
        public static string Authentication_failed_1 {
            get {
                return ResourceManager.GetString("Authentication_failed_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is suspended.
        /// </summary>
        public static string Authentication_failed_2 {
            get {
                return ResourceManager.GetString("Authentication_failed_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has expired.
        /// </summary>
        public static string Authentication_failed_3 {
            get {
                return ResourceManager.GetString("Authentication_failed_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions in the system.
        /// </summary>
        public static string Authentication_failed_4 {
            get {
                return ResourceManager.GetString("Authentication_failed_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup method.
        /// </summary>
        public static string Backup_method {
            get {
                return ResourceManager.GetString("Backup_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank holiday management.
        /// </summary>
        public static string Bank_holiday_management {
            get {
                return ResourceManager.GetString("Bank_holiday_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEAC nationality management.
        /// </summary>
        public static string BEAC_nationality_management {
            get {
                return ResourceManager.GetString("BEAC_nationality_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begining period.
        /// </summary>
        public static string Begining_period {
            get {
                return ResourceManager.GetString("Begining_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        public static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch manager.
        /// </summary>
        public static string Branch_manager {
            get {
                return ResourceManager.GetString("Branch_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget directionate management.
        /// </summary>
        public static string Budget_directionate_management {
            get {
                return ResourceManager.GetString("Budget_directionate_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cautioned.
        /// </summary>
        public static string Cautioned {
            get {
                return ResourceManager.GetString("Cautioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm action.
        /// </summary>
        public static string Confirm_action {
            get {
                return ResourceManager.GetString("Confirm_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection status.
        /// </summary>
        public static string Connection_status {
            get {
                return ResourceManager.GetString("Connection_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control number of loans.
        /// </summary>
        public static string Control_number_of_loans {
            get {
                return ResourceManager.GetString("Control_number_of_loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control session.
        /// </summary>
        public static string Control_session {
            get {
                return ResourceManager.GetString("Control_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept and continue.
        /// </summary>
        public static string Cookie_button {
            get {
                return ResourceManager.GetString("Cookie_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to offer you the best experience, our application uses cookies. By continuing to use this application, you agree to our use of cookies..
        /// </summary>
        public static string Cookie_message {
            get {
                return ResourceManager.GetString("Cookie_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2018 All rights reserved &lt;b&gt;Better Planning Ltd&lt;/b&gt;.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count account.
        /// </summary>
        public static string Count_account {
            get {
                return ResourceManager.GetString("Count_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count page number statement.
        /// </summary>
        public static string Count_page_number_statement {
            get {
                return ResourceManager.GetString("Count_page_number_statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country zone.
        /// </summary>
        public static string Country_zone {
            get {
                return ResourceManager.GetString("Country_zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string Creation_date {
            get {
                return ResourceManager.GetString("Creation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current currency.
        /// </summary>
        public static string Current_currency {
            get {
                return ResourceManager.GetString("Current_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer max credit.
        /// </summary>
        public static string Customer_max_credit {
            get {
                return ResourceManager.GetString("Customer_max_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer max debit.
        /// </summary>
        public static string Customer_max_debit {
            get {
                return ResourceManager.GetString("Customer_max_debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer overdraft limit.
        /// </summary>
        public static string Customer_overdraft_limit {
            get {
                return ResourceManager.GetString("Customer_overdraft_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data required.
        /// </summary>
        public static string Data_required {
            get {
                return ResourceManager.GetString("Data_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        public static string Del_ {
            get {
                return ResourceManager.GetString("Del_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete menus.
        /// </summary>
        public static string Delete_menus {
            get {
                return ResourceManager.GetString("Delete_menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devise management.
        /// </summary>
        public static string Devise_management {
            get {
                return ResourceManager.GetString("Devise_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string Differential {
            get {
                return ResourceManager.GetString("Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directionate head.
        /// </summary>
        public static string Directionate_head {
            get {
                return ResourceManager.GetString("Directionate_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dormant period.
        /// </summary>
        public static string Dormant_period {
            get {
                return ResourceManager.GetString("Dormant_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economic activities management.
        /// </summary>
        public static string Economic_activities_management {
            get {
                return ResourceManager.GetString("Economic_activities_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee historical access.
        /// </summary>
        public static string Employee_historical_access {
            get {
                return ResourceManager.GetString("Employee_historical_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End days.
        /// </summary>
        public static string End_days {
            get {
                return ResourceManager.GetString("End_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending date.
        /// </summary>
        public static string Ending_date {
            get {
                return ResourceManager.GetString("Ending_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending period.
        /// </summary>
        public static string Ending_period {
            get {
                return ResourceManager.GetString("Ending_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erasing.
        /// </summary>
        public static string Erasing {
            get {
                return ResourceManager.GetString("Erasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing, please contact the administrator..
        /// </summary>
        public static string Error_message_notification {
            get {
                return ResourceManager.GetString("Error_message_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A communication error has occurred.
        /// </summary>
        public static string Error_server_message {
            get {
                return ResourceManager.GetString("Error_server_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing data.
        /// </summary>
        public static string Existing_data {
            get {
                return ResourceManager.GetString("Existing_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing day.
        /// </summary>
        public static string Existing_day {
            get {
                return ResourceManager.GetString("Existing_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration duration.
        /// </summary>
        public static string Expiration_duration {
            get {
                return ResourceManager.GetString("Expiration_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscals exercice management.
        /// </summary>
        public static string Fiscals_exercice_management {
            get {
                return ResourceManager.GetString("Fiscals_exercice_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        public static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garantie deposit.
        /// </summary>
        public static string Garantie_deposit {
            get {
                return ResourceManager.GetString("Garantie_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General banking parameters.
        /// </summary>
        public static string General_banking_parameters {
            get {
                return ResourceManager.GetString("General_banking_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General parameters.
        /// </summary>
        public static string General_parameters {
            get {
                return ResourceManager.GetString("General_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        public static string Greater_than {
            get {
                return ResourceManager.GetString("Greater_than", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantee type management.
        /// </summary>
        public static string Guarantee_type_management {
            get {
                return ResourceManager.GetString("Guarantee_type_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution management.
        /// </summary>
        public static string Institution_management {
            get {
                return ResourceManager.GetString("Institution_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutional unit management.
        /// </summary>
        public static string Institutional_unit_management {
            get {
                return ResourceManager.GetString("Institutional_unit_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        public static string Internal_error {
            get {
                return ResourceManager.GetString("Internal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date.
        /// </summary>
        public static string Invalid_date {
            get {
                return ResourceManager.GetString("Invalid_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IP_Address {
            get {
                return ResourceManager.GetString("IP_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journals recording management.
        /// </summary>
        public static string Journals_recording_management {
            get {
                return ResourceManager.GetString("Journals_recording_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judicial products management.
        /// </summary>
        public static string Judicial_products_management {
            get {
                return ResourceManager.GetString("Judicial_products_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last transaction.
        /// </summary>
        public static string Last_transaction {
            get {
                return ResourceManager.GetString("Last_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of credit max amount.
        /// </summary>
        public static string Line_of_credit_max_amount {
            get {
                return ResourceManager.GetString("Line_of_credit_max_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of records.
        /// </summary>
        public static string List_of_records {
            get {
                return ResourceManager.GetString("List_of_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing.
        /// </summary>
        public static string Listing {
            get {
                return ResourceManager.GetString("Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litigation.
        /// </summary>
        public static string Litigation {
            get {
                return ResourceManager.GetString("Litigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litigation period.
        /// </summary>
        public static string Litigation_period {
            get {
                return ResourceManager.GetString("Litigation_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        public static string Loan {
            get {
                return ResourceManager.GetString("Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan limit amount.
        /// </summary>
        public static string Loan_limit_amount {
            get {
                return ResourceManager.GetString("Loan_limit_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans provision classification management.
        /// </summary>
        public static string Loans_provision_classification_management {
            get {
                return ResourceManager.GetString("Loans_provision_classification_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans purpose management.
        /// </summary>
        public static string Loans_purpose_management {
            get {
                return ResourceManager.GetString("Loans_purpose_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans type management.
        /// </summary>
        public static string Loans_type_management {
            get {
                return ResourceManager.GetString("Loans_type_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to the application.
        /// </summary>
        public static string Login_application {
            get {
                return ResourceManager.GetString("Login_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lst.
        /// </summary>
        public static string Lst_ {
            get {
                return ResourceManager.GetString("Lst_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of banking parameters.
        /// </summary>
        public static string Management_of_banking_parameters {
            get {
                return ResourceManager.GetString("Management_of_banking_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu group.
        /// </summary>
        public static string Menu_group {
            get {
                return ResourceManager.GetString("Menu_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu management.
        /// </summary>
        public static string Menu_Management {
            get {
                return ResourceManager.GetString("Menu_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        public static string Mod_ {
            get {
                return ResourceManager.GetString("Mod_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify custom attributes in branch.
        /// </summary>
        public static string Modify_custom_attributes_in_branch {
            get {
                return ResourceManager.GetString("Modify_custom_attributes_in_branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module management.
        /// </summary>
        public static string Module_Management {
            get {
                return ResourceManager.GetString("Module_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage.
        /// </summary>
        public static string Mortgage {
            get {
                return ResourceManager.GetString("Mortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary privilege load action.
        /// </summary>
        public static string Necessary_privilege_loading_action {
            get {
                return ResourceManager.GetString("Necessary_privilege_loading_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New menus.
        /// </summary>
        public static string New_menus {
            get {
                return ResourceManager.GetString("New_menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night run posting options.
        /// </summary>
        public static string Night_run_posting_options {
            get {
                return ResourceManager.GetString("Night_run_posting_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes have been made.
        /// </summary>
        public static string No_changes_have_been_made {
            get {
                return ResourceManager.GetString("No_changes_have_been_made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item selected.
        /// </summary>
        public static string No_item_selected {
            get {
                return ResourceManager.GetString("No_item_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payment period.
        /// </summary>
        public static string No_payment_period {
            get {
                return ResourceManager.GetString("No_payment_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number day before write off.
        /// </summary>
        public static string Number_day_before_write_off {
            get {
                return ResourceManager.GetString("Number_day_before_write_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object not found.
        /// </summary>
        public static string Object_not_found {
            get {
                return ResourceManager.GetString("Object_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open back date.
        /// </summary>
        public static string Open_back_date {
            get {
                return ResourceManager.GetString("Open_back_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open back working date.
        /// </summary>
        public static string Open_back_working_date {
            get {
                return ResourceManager.GetString("Open_back_working_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open branch.
        /// </summary>
        public static string Open_branch {
            get {
                return ResourceManager.GetString("Open_branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string Page_not_found {
            get {
                return ResourceManager.GetString("Page_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE PAGE YOU TRY TO ACCESS IS NOT AVAILABLE.
        /// </summary>
        public static string Page_not_found_message {
            get {
                return ResourceManager.GetString("Page_not_found_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password expiration.
        /// </summary>
        public static string Password_expiration {
            get {
                return ResourceManager.GetString("Password_expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path first backup.
        /// </summary>
        public static string Path_first_backup {
            get {
                return ResourceManager.GetString("Path_first_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path last backup.
        /// </summary>
        public static string Path_last_backup {
            get {
                return ResourceManager.GetString("Path_last_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays management.
        /// </summary>
        public static string Pays_management {
            get {
                return ResourceManager.GetString("Pays_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodicity.
        /// </summary>
        public static string Periodicity {
            get {
                return ResourceManager.GetString("Periodicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied.
        /// </summary>
        public static string Permission_denied {
            get {
                return ResourceManager.GetString("Permission_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission to list records denied.
        /// </summary>
        public static string Permission_to_list_records_denied {
            get {
                return ResourceManager.GetString("Permission_to_list_records_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone id.
        /// </summary>
        public static string Phone_id {
            get {
                return ResourceManager.GetString("Phone_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical products management.
        /// </summary>
        public static string Physical_products_management {
            get {
                return ResourceManager.GetString("Physical_products_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post loan litigation.
        /// </summary>
        public static string Post_loan_litigation {
            get {
                return ResourceManager.GetString("Post_loan_litigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post local collection.
        /// </summary>
        public static string Post_local_collection {
            get {
                return ResourceManager.GetString("Post_local_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post term and time deposits.
        /// </summary>
        public static string Post_term_and_time_deposits {
            get {
                return ResourceManager.GetString("Post_term_and_time_deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.O. Box.
        /// </summary>
        public static string Postal_code {
            get {
                return ResourceManager.GetString("Postal_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege management.
        /// </summary>
        public static string Privilege_management {
            get {
                return ResourceManager.GetString("Privilege_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process in production.
        /// </summary>
        public static string Process_in_production {
            get {
                return ResourceManager.GetString("Process_in_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product information.
        /// </summary>
        public static string Product_information {
            get {
                return ResourceManager.GetString("Product_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prt.
        /// </summary>
        public static string Prt_ {
            get {
                return ResourceManager.GetString("Prt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        public static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real safety.
        /// </summary>
        public static string Real_safety {
            get {
                return ResourceManager.GetString("Real_safety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve interest.
        /// </summary>
        public static string Reserve_interest {
            get {
                return ResourceManager.GetString("Reserve_interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve interest post method.
        /// </summary>
        public static string Reserve_interest_post_method {
            get {
                return ResourceManager.GetString("Reserve_interest_post_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role and privilege management.
        /// </summary>
        public static string Role_and_privilege_management {
            get {
                return ResourceManager.GetString("Role_and_privilege_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule management.
        /// </summary>
        public static string Rule_Management {
            get {
                return ResourceManager.GetString("Rule_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a role.
        /// </summary>
        public static string Search_a_role {
            get {
                return ResourceManager.GetString("Search_a_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by.
        /// </summary>
        public static string Search_by {
            get {
                return ResourceManager.GetString("Search_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session duration.
        /// </summary>
        public static string Session_duration {
            get {
                return ResourceManager.GetString("Session_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Sign_Out {
            get {
                return ResourceManager.GetString("Sign_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing amount.
        /// </summary>
        public static string Signing_amount {
            get {
                return ResourceManager.GetString("Signing_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing authority.
        /// </summary>
        public static string Signing_authority {
            get {
                return ResourceManager.GetString("Signing_authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing authority management.
        /// </summary>
        public static string Signing_authority_management {
            get {
                return ResourceManager.GetString("Signing_authority_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS banking.
        /// </summary>
        public static string SMS_banking {
            get {
                return ResourceManager.GetString("SMS_banking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start days.
        /// </summary>
        public static string Start_days {
            get {
                return ResourceManager.GetString("Start_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting date.
        /// </summary>
        public static string Starting_date {
            get {
                return ResourceManager.GetString("Starting_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State guarantee.
        /// </summary>
        public static string State_guarantee {
            get {
                return ResourceManager.GetString("State_guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement page count.
        /// </summary>
        public static string Statement_page_count {
            get {
                return ResourceManager.GetString("Statement_page_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must not exceed.
        /// </summary>
        public static string The_file_must_not_exceed {
            get {
                return ResourceManager.GetString("The_file_must_not_exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object must have a unique id.
        /// </summary>
        public static string The_object_must_have_a_unique_id {
            get {
                return ResourceManager.GetString("The_object_must_have_a_unique_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has just ended.
        /// </summary>
        public static string The_session_has_just_ended {
            get {
                return ResourceManager.GetString("The_session_has_just_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is suspended.
        /// </summary>
        public static string This_account_is_suspended {
            get {
                return ResourceManager.GetString("This_account_is_suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This day not exist.
        /// </summary>
        public static string This_day_not_exist {
            get {
                return ResourceManager.GetString("This_day_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product will be apply to the following transactions.
        /// </summary>
        public static string This_product_will_be_apply_to_the_following_transactions {
            get {
                return ResourceManager.GetString("This_product_will_be_apply_to_the_following_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time deposit.
        /// </summary>
        public static string Time_deposit {
            get {
                return ResourceManager.GetString("Time_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title management.
        /// </summary>
        public static string Title_management {
            get {
                return ResourceManager.GetString("Title_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To log in.
        /// </summary>
        public static string To_log_in {
            get {
                return ResourceManager.GetString("To_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town management.
        /// </summary>
        public static string Town_management {
            get {
                return ResourceManager.GetString("Town_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        public static string Unpaid {
            get {
                return ResourceManager.GetString("Unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update customer position.
        /// </summary>
        public static string Update_customer_position {
            get {
                return ResourceManager.GetString("Update_customer_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use central version.
        /// </summary>
        public static string Use_central_version {
            get {
                return ResourceManager.GetString("Use_central_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use check booklet.
        /// </summary>
        public static string Use_check_booklet {
            get {
                return ResourceManager.GetString("Use_check_booklet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use cobac litigation method.
        /// </summary>
        public static string Use_cobac_litigation_method {
            get {
                return ResourceManager.GetString("Use_cobac_litigation_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User management.
        /// </summary>
        public static string User_Management {
            get {
                return ResourceManager.GetString("User_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.A.T..
        /// </summary>
        public static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Union country zone management.
        /// </summary>
        public static string Western_Union_country_zone_management {
            get {
                return ResourceManager.GetString("Western_Union_country_zone_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be disconnected.
        /// </summary>
        public static string You_will_be_disconnected {
            get {
                return ResourceManager.GetString("You_will_be_disconnected", resourceCulture);
            }
        }
    }
}
