//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInformation
    {
        public string TableName { get; set; }
        public string AccountNumber { get; set; }
        public string AccountKey { get; set; }
        public string AccountName { get; set; }
        public int Series { get; set; }
        public string CustomerAccount { get; set; }
        public string Statut { get; set; }
    }
}
