//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class agencebb
    {
        public double agcod { get; set; }
        public string aglib { get; set; }
        public string agadr { get; set; }
        public string agbp { get; set; }
        public string agville { get; set; }
        public string agpays { get; set; }
        public string agtelp { get; set; }
        public string agfax { get; set; }
        public Nullable<System.DateTime> agdcr { get; set; }
        public Nullable<int> Piece { get; set; }
        public Nullable<System.DateTime> agdats { get; set; }
        public Nullable<double> ligne { get; set; }
        public string CobacID { get; set; }
        public string AgComp { get; set; }
        public string BeacId { get; set; }
        public Nullable<System.DateTime> DateCompensation { get; set; }
        public Nullable<System.DateTime> DateVeilleComp { get; set; }
        public string CurrentBr { get; set; }
        public string motto { get; set; }
        public string publicite { get; set; }
        public string institution { get; set; }
        public string typesociete { get; set; }
        public string cptecltres { get; set; }
        public Nullable<int> CurrentManager { get; set; }
        public string CurrentManagerName { get; set; }
        public byte[] Logoagence { get; set; }
        public string FiscalID { get; set; }
        public string BudgetID { get; set; }
        public string CompanyAbbreviation { get; set; }
        public string PduitCash { get; set; }
        public string Sauvegarde { get; set; }
        public string ControlBranchAcct { get; set; }
        public string BranchSituation { get; set; }
        public Nullable<System.DateTime> DateDerFerm { get; set; }
        public Nullable<System.DateTime> DateTransfert { get; set; }
        public Nullable<int> Employe { get; set; }
        public string libEmploye { get; set; }
        public Nullable<System.DateTime> DateJourEnCours { get; set; }
        public string brabbreviation { get; set; }
        public string cptecltresint { get; set; }
        public string TransfPhone { get; set; }
        public string PathLogo { get; set; }
        public Nullable<int> SizeLogo { get; set; }
        public string PhotoName { get; set; }
    }
}
