//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationTable
    {
        public string ApplicationName { get; set; }
        public string ApplicationTableName { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string privFunction { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public string MenuName { get; set; }
        public string privfunctionfr { get; set; }
        public decimal Serie { get; set; }
    }
}
