//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditCotation
    {
        public string Agence { get; set; }
        public int Matricule { get; set; }
        public string LibEmploye { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string LibPrivilege { get; set; }
        public string Qualite { get; set; }
        public string LibQualite { get; set; }
        public string Privilege { get; set; }
        public Nullable<short> Employe { get; set; }
        public string NomEmploye { get; set; }
        public Nullable<System.DateTime> DateTransfert { get; set; }
        public string RowStatus { get; set; }
        public Nullable<int> serie { get; set; }
        public decimal IdAudit { get; set; }
        public Nullable<System.DateTime> DateAudit { get; set; }
    }
}
