//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditProductTxn
    {
        public string Agence { get; set; }
        public string Caisse { get; set; }
        public int Serie { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Reference { get; set; }
        public string TypeVir { get; set; }
        public string OptnType { get; set; }
        public Nullable<System.DateTime> DateOperation { get; set; }
        public string Description { get; set; }
        public string NomCaissier { get; set; }
        public string LibCaisse { get; set; }
        public string LibAgence { get; set; }
        public string SendName { get; set; }
        public string ReceivName { get; set; }
        public Nullable<short> AgenceRecep { get; set; }
        public string CpteGL { get; set; }
        public string CleCpte { get; set; }
        public string LibCpteGL { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string CodeMaj { get; set; }
        public string Employe { get; set; }
        public string LibEmploye { get; set; }
        public string TxnNo { get; set; }
        public Nullable<System.DateTime> DateTransfert { get; set; }
        public string RowStatus { get; set; }
        public Nullable<double> comamount { get; set; }
        public string codemajcom { get; set; }
        public Nullable<double> tvaamount { get; set; }
        public string CpteCaisse { get; set; }
        public string CleCpteCaisse { get; set; }
        public string LibCpteCaisse { get; set; }
        public string CodePays { get; set; }
        public string LibellePays { get; set; }
        public Nullable<double> PayAmount1 { get; set; }
        public Nullable<double> ComAmt1 { get; set; }
        public Nullable<double> TvaAmt1 { get; set; }
    }
}
