//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditPostLoan
    {
        public string Agence { get; set; }
        public string LibAgence { get; set; }
        public string CpteJumelle { get; set; }
        public string Denomination { get; set; }
        public decimal Serie { get; set; }
        public string IDaudit { get; set; }
        public Nullable<System.DateTime> Datetransfert { get; set; }
        public string RowStatus { get; set; }
        public System.DateTime DateContrat { get; set; }
        public double Amount { get; set; }
        public short Duree { get; set; }
        public string Periodicite { get; set; }
        public string Status { get; set; }
        public string Matricule { get; set; }
        public string LibEmploye { get; set; }
        public string LoanProvenance { get; set; }
        public string rqcomments { get; set; }
        public string vlcomments { get; set; }
        public string dbcomments { get; set; }
        public string NameDisburse { get; set; }
        public string MatDisburse { get; set; }
        public Nullable<System.DateTime> DateDis { get; set; }
        public string NameApprouval { get; set; }
        public string MatApprouval { get; set; }
        public Nullable<System.DateTime> DateApprouval { get; set; }
        public Nullable<System.DateTime> dateaudit { get; set; }
    }
}
