//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditServerStatu
    {
        public string StatePostOperation { get; set; }
        public Nullable<System.DateTime> DateState { get; set; }
        public Nullable<System.DateTime> HeureState { get; set; }
        public string Status { get; set; }
        public Nullable<int> Employe { get; set; }
        public string LibEmploye { get; set; }
        public string RowStatus { get; set; }
        public int Serie { get; set; }
    }
}
