//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditEmploye
    {
        public string Agence { get; set; }
        public string Matricule { get; set; }
        public string NomPrenom { get; set; }
        public string Qualite { get; set; }
        public Nullable<short> SecurityLevel { get; set; }
        public string MotPasse { get; set; }
        public string LibQualite { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> DateAttMP { get; set; }
        public string Suspension { get; set; }
        public Nullable<short> DureeMP { get; set; }
        public string Employe { get; set; }
        public string NomEmploye { get; set; }
        public Nullable<double> MaximumLimit { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateSuspension { get; set; }
        public Nullable<System.DateTime> ServerDate { get; set; }
        public string ComputerName { get; set; }
        public Nullable<System.DateTime> DateTransfert { get; set; }
        public string RowStatus { get; set; }
        public string AllocateComputer { get; set; }
        public string EmpAccess { get; set; }
        public string sessiontype { get; set; }
        public Nullable<int> serie { get; set; }
        public decimal IdAudit { get; set; }
        public Nullable<System.DateTime> DateAudit { get; set; }
        public string OpenBranch { get; set; }
        public string BackDAte { get; set; }
        public string BackDAteWk { get; set; }
        public string Auth { get; set; }
    }
}
