//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditCatCpte
    {
        public short CatCpte { get; set; }
        public string Designation { get; set; }
        public string DesignAnglais { get; set; }
        public string CpteColClt { get; set; }
        public string CleColClt { get; set; }
        public string LibCpteColClt { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Employe { get; set; }
        public string NomEmploye { get; set; }
        public Nullable<System.DateTime> DateTransfert { get; set; }
        public string RowStatus { get; set; }
        public int Serie { get; set; }
    }
}
