//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditAgence
    {
        public string agcod { get; set; }
        public string aglib { get; set; }
        public string agadr { get; set; }
        public string agbp { get; set; }
        public string agville { get; set; }
        public string agpays { get; set; }
        public string agtelp { get; set; }
        public string agfax { get; set; }
        public Nullable<System.DateTime> agdcr { get; set; }
        public Nullable<System.DateTime> agdats { get; set; }
        public string CobacID { get; set; }
        public string BeacId { get; set; }
        public string cptecltres { get; set; }
        public string Employe { get; set; }
        public string BranchSituation { get; set; }
        public Nullable<System.DateTime> DateDerFerm { get; set; }
        public Nullable<System.DateTime> DateJourEnCours { get; set; }
        public string Sauvegarde { get; set; }
        public string ControlBranchAcct { get; set; }
        public string cptecltresint { get; set; }
        public string TransfPhone { get; set; }
        public Nullable<System.DateTime> ServerDate { get; set; }
        public string ServerOpen { get; set; }
        public Nullable<System.DateTime> ServerBackDate { get; set; }
        public string BackOpen { get; set; }
        public decimal Serie { get; set; }
        public string RowStatus { get; set; }
    }
}
