//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditCompany
    {
        public string Agence { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> Employe { get; set; }
        public string NomEmploye { get; set; }
        public Nullable<double> Operationcharge { get; set; }
        public string cptegl { get; set; }
        public string clecpte { get; set; }
        public string libcptegl { get; set; }
        public Nullable<System.DateTime> DateTransfert { get; set; }
        public string RowStatus { get; set; }
        public Nullable<int> serie { get; set; }
        public decimal IdAudit { get; set; }
        public Nullable<System.DateTime> DateAudit { get; set; }
        public string operationtype { get; set; }
        public string TreatmentType { get; set; }
    }
}
