//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditdevise
    {
        public string devcod { get; set; }
        public string devsign { get; set; }
        public Nullable<System.DateTime> devdate { get; set; }
        public Nullable<double> devcm { get; set; }
        public Nullable<double> devcac { get; set; }
        public Nullable<double> devcab { get; set; }
        public Nullable<double> devcvc { get; set; }
        public Nullable<double> devcvb { get; set; }
        public string devlib { get; set; }
        public Nullable<double> DevCashBuy { get; set; }
        public Nullable<double> DevTCSSell { get; set; }
        public Nullable<double> DevIssueDraft { get; set; }
        public Nullable<double> DevInComingTRF { get; set; }
        public Nullable<double> DevCashSell { get; set; }
        public Nullable<double> DevTCSBuy { get; set; }
        public Nullable<double> DevDraftOnColl { get; set; }
        public Nullable<double> DevOutgoingTRF { get; set; }
        public string CurrentCurrency { get; set; }
        public int Series { get; set; }
        public string Numdevise { get; set; }
        public Nullable<System.DateTime> DateTransfert { get; set; }
        public string RowStatus { get; set; }
    }
}
