//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOTRANSFERT
    {
        public string CODEAUTOTRF { get; set; }
        public int ProductCode { get; set; }
        public string CatClient { get; set; }
        public string DECRIPTIONTRF { get; set; }
        public string LibProduct { get; set; }
        public string CustomerType { get; set; }
        public string LibCatClient { get; set; }
        public Nullable<double> AMOUNTTRF { get; set; }
        public string PERIODICITY { get; set; }
        public Nullable<int> CODEPRODDEST { get; set; }
        public string LibProductTrf { get; set; }
        public string TYPEOP { get; set; }
    }
}
