//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOMATICTRFHIST
    {
        public string Agenced { get; set; }
        public string Cpted { get; set; }
        public string NomCompted { get; set; }
        public string Agencer { get; set; }
        public string Cpter { get; set; }
        public string NomCompter { get; set; }
        public string Employe { get; set; }
        public string Description { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<decimal> Auto1 { get; set; }
        public decimal Auto { get; set; }
        public Nullable<System.DateTime> datedt { get; set; }
    }
}
