//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BankingEntities : DbContext
    {
        public BankingEntities()
            : base("name=BankingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiviteEco> ActiviteEcoes { get; set; }
        public virtual DbSet<agence> agences { get; set; }
        public virtual DbSet<agencebb> agencebbs { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationTable> ApplicationTables { get; set; }
        public virtual DbSet<AuditAgence> AuditAgences { get; set; }
        public virtual DbSet<AutoCred> AutoCreds { get; set; }
        public virtual DbSet<AUTOMATICTRF> AUTOMATICTRFs { get; set; }
        public virtual DbSet<AUTOMATICTRFHIST> AUTOMATICTRFHISTs { get; set; }
        public virtual DbSet<AUTOMATICTRFHISTPRODUCT> AUTOMATICTRFHISTPRODUCTs { get; set; }
        public virtual DbSet<AUTOMATICTRFTPRODUCT> AUTOMATICTRFTPRODUCTs { get; set; }
        public virtual DbSet<AUTOTRANSFERT> AUTOTRANSFERTs { get; set; }
        public virtual DbSet<Avaliste> Avalistes { get; set; }
        public virtual DbSet<Billetage> Billetages { get; set; }
        public virtual DbSet<BilletHist> BilletHists { get; set; }
        public virtual DbSet<billinglist> billinglists { get; set; }
        public virtual DbSet<BillingOptiono> BillingOptionoes { get; set; }
        public virtual DbSet<BonCaisse> BonCaisses { get; set; }
        public virtual DbSet<BranchAcct> BranchAccts { get; set; }
        public virtual DbSet<Caisse> Caisses { get; set; }
        public virtual DbSet<CaisseMaxLimCusto> CaisseMaxLimCustoes { get; set; }
        public virtual DbSet<CatCpte> CatCptes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CautionAval> CautionAvals { get; set; }
        public virtual DbSet<CC> CCs { get; set; }
        public virtual DbSet<CheqTrait> CheqTraits { get; set; }
        public virtual DbSet<ClientBnk> ClientBnks { get; set; }
        public virtual DbSet<ClientBnk1> ClientBnk1 { get; set; }
        public virtual DbSet<CMOpDevise> CMOpDevises { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Compensation> Compensations { get; set; }
        public virtual DbSet<ConfigLoanPurpose> ConfigLoanPurposes { get; set; }
        public virtual DbSet<ConfigTypeLoan> ConfigTypeLoans { get; set; }
        public virtual DbSet<Contentieu> Contentieux { get; set; }
        public virtual DbSet<CorrespBnk> CorrespBnks { get; set; }
        public virtual DbSet<CorrespTable> CorrespTables { get; set; }
        public virtual DbSet<Cotation> Cotations { get; set; }
        public virtual DbSet<CountryZone> CountryZones { get; set; }
        public virtual DbSet<CpteClt> CpteClts { get; set; }
        public virtual DbSet<CpteClt1> CpteClt1 { get; set; }
        public virtual DbSet<CpteCltHist> CpteCltHists { get; set; }
        public virtual DbSet<CpteCltHistArch> CpteCltHistArches { get; set; }
        public virtual DbSet<CpteCorrespBnk> CpteCorrespBnks { get; set; }
        public virtual DbSet<Credit> Credits { get; set; }
        public virtual DbSet<CumulCpteClthist> CumulCpteClthists { get; set; }
        public virtual DbSet<CumulCpteGlhist> CumulCpteGlhists { get; set; }
        public virtual DbSet<DataImport> DataImports { get; set; }
        public virtual DbSet<DataImportSTO> DataImportSTOes { get; set; }
        public virtual DbSet<DataImportSTObckp> DataImportSTObckps { get; set; }
        public virtual DbSet<DepotTerme> DepotTermes { get; set; }
        public virtual DbSet<DepRetGeneral> DepRetGenerals { get; set; }
        public virtual DbSet<DepRetGeneralBi> DepRetGeneralBis { get; set; }
        public virtual DbSet<devise> devises { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<EcritCptable> EcritCptables { get; set; }
        public virtual DbSet<EcritCptableBi> EcritCptableBis { get; set; }
        public virtual DbSet<EcritCptableBisArch> EcritCptableBisArches { get; set; }
        public virtual DbSet<EmetteurTCSComex> EmetteurTCSComexes { get; set; }
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<EMPLOYE_MODULE> EMPLOYE_MODULE { get; set; }
        public virtual DbSet<EncoursCustomer> EncoursCustomers { get; set; }
        public virtual DbSet<EODProcess> EODProcesses { get; set; }
        public virtual DbSet<ErrTabSalTemp> ErrTabSalTemps { get; set; }
        public virtual DbSet<exclumanualpostgl> exclumanualpostgls { get; set; }
        public virtual DbSet<ExcluTellerPostGL> ExcluTellerPostGLs { get; set; }
        public virtual DbSet<fclttmp> fclttmps { get; set; }
        public virtual DbSet<fcptg> fcptgs { get; set; }
        public virtual DbSet<Fcptg99> Fcptg99 { get; set; }
        public virtual DbSet<fcptgcopec> fcptgcopecs { get; set; }
        public virtual DbSet<FCPTGTEMP> FCPTGTEMPs { get; set; }
        public virtual DbSet<FcptgTmp> FcptgTmps { get; set; }
        public virtual DbSet<FTableAsset> FTableAssets { get; set; }
        public virtual DbSet<FTableLiability> FTableLiabilities { get; set; }
        public virtual DbSet<GarantieAccount> GarantieAccounts { get; set; }
        public virtual DbSet<Garanty> Garanties { get; set; }
        public virtual DbSet<Garantieso> Garantiesoes { get; set; }
        public virtual DbSet<GeneralPara> GeneralParas { get; set; }
        public virtual DbSet<GeneralTrxn> GeneralTrxns { get; set; }
        public virtual DbSet<GeneralTrxnBi> GeneralTrxnBis { get; set; }
        public virtual DbSet<GlHist> GlHists { get; set; }
        public virtual DbSet<GlHistArch> GlHistArches { get; set; }
        public virtual DbSet<GlHistBi> GlHistBis { get; set; }
        public virtual DbSet<GlobexBranch> GlobexBranches { get; set; }
        public virtual DbSet<HistoCaisse> HistoCaisses { get; set; }
        public virtual DbSet<HistProvLoan> HistProvLoans { get; set; }
        public virtual DbSet<Immo> Immoes { get; set; }
        public virtual DbSet<ImmoHist> ImmoHists { get; set; }
        public virtual DbSet<Impaye> Impayes { get; set; }
        public virtual DbSet<IncExpAcc> IncExpAccs { get; set; }
        public virtual DbSet<InComeloan> InComeloans { get; set; }
        public virtual DbSet<InComeSM> InComeSMS { get; set; }
        public virtual DbSet<Indisponible> Indisponibles { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<IntegrateFile> IntegrateFiles { get; set; }
        public virtual DbSet<InteretCredit> InteretCredits { get; set; }
        public virtual DbSet<IntSMSJournal> IntSMSJournals { get; set; }
        public virtual DbSet<JnalRembLoan> JnalRembLoans { get; set; }
        public virtual DbSet<JnlInteret> JnlInterets { get; set; }
        public virtual DbSet<JnlInteretEBANKING> JnlInteretEBANKINGs { get; set; }
        public virtual DbSet<JnlInteretSM> JnlInteretSMS { get; set; }
        public virtual DbSet<JourFerie> JourFeries { get; set; }
        public virtual DbSet<journal> journals { get; set; }
        public virtual DbSet<LoanPortfolioClassification> LoanPortfolioClassifications { get; set; }
        public virtual DbSet<LoanProvisionClassification> LoanProvisionClassifications { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<ManualCrInterest> ManualCrInterests { get; set; }
        public virtual DbSet<MODULE> MODULEs { get; set; }
        public virtual DbSet<MODULE_MENU> MODULE_MENU { get; set; }
        public virtual DbSet<MODULE_MENU_TMP> MODULE_MENU_TMP { get; set; }
        public virtual DbSet<MouchardTransact> MouchardTransacts { get; set; }
        public virtual DbSet<NatBEAC> NatBEACs { get; set; }
        public virtual DbSet<NatJur> NatJurs { get; set; }
        public virtual DbSet<nomenposte> nomenpostes { get; set; }
        public virtual DbSet<OpCaisA> OpCaisAs { get; set; }
        public virtual DbSet<OpCaisABi> OpCaisABis { get; set; }
        public virtual DbSet<OpDiversA> OpDiversAs { get; set; }
        public virtual DbSet<OpDiversB> OpDiversBs { get; set; }
        public virtual DbSet<OpDiversG> OpDiversGs { get; set; }
        public virtual DbSet<OutGoingSM> OutGoingSMS { get; set; }
        public virtual DbSet<Parametre> Parametres { get; set; }
        public virtual DbSet<PhotoSign> PhotoSigns { get; set; }
        public virtual DbSet<Piece> Pieces { get; set; }
        public virtual DbSet<PieceB> PieceBs { get; set; }
        public virtual DbSet<PlageBilling> PlageBillings { get; set; }
        public virtual DbSet<PlageCustProdStat> PlageCustProdStats { get; set; }
        public virtual DbSet<PorteFeuilleLocal> PorteFeuilleLocals { get; set; }
        public virtual DbSet<PostLoan> PostLoans { get; set; }
        public virtual DbSet<PreprocesInformation> PreprocesInformations { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<PrivLabel> PrivLabels { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductAttribute> ProductAttributes { get; set; }
        public virtual DbSet<ProductTxn> ProductTxns { get; set; }
        public virtual DbSet<PROFITABILITYGROUP> PROFITABILITYGROUPs { get; set; }
        public virtual DbSet<PROFITABILITYTYPE> PROFITABILITYTYPEs { get; set; }
        public virtual DbSet<ProvCommi> ProvCommis { get; set; }
        public virtual DbSet<ProvisionAccount> ProvisionAccounts { get; set; }
        public virtual DbSet<ProvLoan> ProvLoans { get; set; }
        public virtual DbSet<ProvTrCodeAn> ProvTrCodeAns { get; set; }
        public virtual DbSet<Qualite> Qualites { get; set; }
        public virtual DbSet<RembAnticipe> RembAnticipes { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<SalTemp> SalTemps { get; set; }
        public virtual DbSet<SalTempBr> SalTempBrs { get; set; }
        public virtual DbSet<StandingOrder> StandingOrders { get; set; }
        public virtual DbSet<StopPayment> StopPayments { get; set; }
        public virtual DbSet<SummaryJnlPartMember> SummaryJnlPartMembers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TabAmortLitige> TabAmortLitiges { get; set; }
        public virtual DbSet<TabAmortLoan> TabAmortLoans { get; set; }
        public virtual DbSet<tabbilanconfig> tabbilanconfigs { get; set; }
        public virtual DbSet<tabBudgetAllocated> tabBudgetAllocateds { get; set; }
        public virtual DbSet<tabBudgetTransaction> tabBudgetTransactions { get; set; }
        public virtual DbSet<tabCashOptn> tabCashOptns { get; set; }
        public virtual DbSet<tabCashTrancode> tabCashTrancodes { get; set; }
        public virtual DbSet<tabcodegroup> tabcodegroups { get; set; }
        public virtual DbSet<TabColonneTaille> TabColonneTailles { get; set; }
        public virtual DbSet<TabConfigReportCobac> TabConfigReportCobacs { get; set; }
        public virtual DbSet<tabCostCentre> tabCostCentres { get; set; }
        public virtual DbSet<TabCpteMembretmp> TabCpteMembretmps { get; set; }
        public virtual DbSet<TABDEFINEMONTH> TABDEFINEMONTHs { get; set; }
        public virtual DbSet<tabDirectorate> tabDirectorates { get; set; }
        public virtual DbSet<TabDuplicata> TabDuplicatas { get; set; }
        public virtual DbSet<TabErrorModifSize> TabErrorModifSizes { get; set; }
        public virtual DbSet<TabExemptEmployee> TabExemptEmployees { get; set; }
        public virtual DbSet<TabFB> TabFBs { get; set; }
        public virtual DbSet<TabFBAuxBal> TabFBAuxBals { get; set; }
        public virtual DbSet<TabFBClthist> TabFBClthists { get; set; }
        public virtual DbSet<TabFBCrDrClt> TabFBCrDrClts { get; set; }
        public virtual DbSet<TabFBCrDrClthist> TabFBCrDrClthists { get; set; }
        public virtual DbSet<TabFBGlHist> TabFBGlHists { get; set; }
        public virtual DbSet<tabFiscalMaster> tabFiscalMasters { get; set; }
        public virtual DbSet<TabFonctionnaire> TabFonctionnaires { get; set; }
        public virtual DbSet<TabFrequencyEOD> TabFrequencyEODs { get; set; }
        public virtual DbSet<TabJnlPartMember> TabJnlPartMembers { get; set; }
        public virtual DbSet<tabLocationMaster> tabLocationMasters { get; set; }
        public virtual DbSet<TABMEMBERBENEF> TABMEMBERBENEFs { get; set; }
        public virtual DbSet<TabNatClient> TabNatClients { get; set; }
        public virtual DbSet<TabReceiveRate> TabReceiveRates { get; set; }
        public virtual DbSet<TabReceiveRateR> TabReceiveRateRs { get; set; }
        public virtual DbSet<tabreport> tabreports { get; set; }
        public virtual DbSet<TabReportMontantCred> TabReportMontantCreds { get; set; }
        public virtual DbSet<tabServiceMaster> tabServiceMasters { get; set; }
        public virtual DbSet<tabSigningAuthority> tabSigningAuthorities { get; set; }
        public virtual DbSet<tabSundryTransaction> tabSundryTransactions { get; set; }
        public virtual DbSet<Titre> Titres { get; set; }
        public virtual DbSet<Tmp_EcritCptableBis> Tmp_EcritCptableBis { get; set; }
        public virtual DbSet<TmpCompareStat> TmpCompareStats { get; set; }
        public virtual DbSet<TMPCREDIT> TMPCREDITs { get; set; }
        public virtual DbSet<TmpCustBalSheet> TmpCustBalSheets { get; set; }
        public virtual DbSet<TMPCustLoanClassification> TMPCustLoanClassifications { get; set; }
        public virtual DbSet<TmpEmpTransaction> TmpEmpTransactions { get; set; }
        public virtual DbSet<TmpLiqDeclaration> TmpLiqDeclarations { get; set; }
        public virtual DbSet<TmpProfitability> TmpProfitabilities { get; set; }
        public virtual DbSet<TMPSM> TMPSMS { get; set; }
        public virtual DbSet<Trancode> Trancodes { get; set; }
        public virtual DbSet<TRANS_REF> TRANS_REF { get; set; }
        public virtual DbSet<TRANSFERPRODUCT> TRANSFERPRODUCTs { get; set; }
        public virtual DbSet<TransfExt> TransfExts { get; set; }
        public virtual DbSet<TransForce> TransForces { get; set; }
        public virtual DbSet<Translate> Translates { get; set; }
        public virtual DbSet<Trbillinglist> Trbillinglists { get; set; }
        public virtual DbSet<TrCodeAnnexe> TrCodeAnnexes { get; set; }
        public virtual DbSet<TrCodeAnnexeo> TrCodeAnnexeos { get; set; }
        public virtual DbSet<TypeJournal> TypeJournals { get; set; }
        public virtual DbSet<UnionInfo> UnionInfoes { get; set; }
        public virtual DbSet<UnitInst> UnitInsts { get; set; }
        public virtual DbSet<ValidTable> ValidTables { get; set; }
        public virtual DbSet<VaultTxn> VaultTxns { get; set; }
        public virtual DbSet<Ville> Villes { get; set; }
        public virtual DbSet<VirPermanent> VirPermanents { get; set; }
        public virtual DbSet<VirSalaire> VirSalaires { get; set; }
        public virtual DbSet<VirSpont> VirSponts { get; set; }
        public virtual DbSet<VirSpontPer> VirSpontPers { get; set; }
        public virtual DbSet<VirSpontPerHist> VirSpontPerHists { get; set; }
        public virtual DbSet<WorkStation> WorkStations { get; set; }
        public virtual DbSet<WriteoffAccount> WriteoffAccounts { get; set; }
        public virtual DbSet<WriteOffLoan> WriteOffLoans { get; set; }
        public virtual DbSet<AccountInformation> AccountInformations { get; set; }
        public virtual DbSet<Actionnaire> Actionnaires { get; set; }
        public virtual DbSet<AgioRservErrorDormAcct> AgioRservErrorDormAccts { get; set; }
        public virtual DbSet<AssetLocalisation> AssetLocalisations { get; set; }
        public virtual DbSet<AssetType> AssetTypes { get; set; }
        public virtual DbSet<AuditAutoCred> AuditAutoCreds { get; set; }
        public virtual DbSet<AuditBonCaisse> AuditBonCaisses { get; set; }
        public virtual DbSet<AuditCatCpte> AuditCatCptes { get; set; }
        public virtual DbSet<AuditClientBnk> AuditClientBnks { get; set; }
        public virtual DbSet<AuditCompany> AuditCompanies { get; set; }
        public virtual DbSet<AuditContentieu> AuditContentieux { get; set; }
        public virtual DbSet<AuditCotation> AuditCotations { get; set; }
        public virtual DbSet<AuditCpteClt> AuditCpteClts { get; set; }
        public virtual DbSet<AuditCpteCltHist> AuditCpteCltHists { get; set; }
        public virtual DbSet<AuditCredit> AuditCredits { get; set; }
        public virtual DbSet<AuditDepotTerme> AuditDepotTermes { get; set; }
        public virtual DbSet<Auditdevise> Auditdevises { get; set; }
        public virtual DbSet<AuditEcritCptable> AuditEcritCptables { get; set; }
        public virtual DbSet<AuditEmploye> AuditEmployes { get; set; }
        public virtual DbSet<AuditEmpPrivSet> AuditEmpPrivSets { get; set; }
        public virtual DbSet<Auditfcptg> Auditfcptgs { get; set; }
        public virtual DbSet<AuditGlHist> AuditGlHists { get; set; }
        public virtual DbSet<AuditHistoCaisse> AuditHistoCaisses { get; set; }
        public virtual DbSet<AuditImpaye> AuditImpayes { get; set; }
        public virtual DbSet<AuditIntegrateFile> AuditIntegrateFiles { get; set; }
        public virtual DbSet<AuditJnalRembLoan> AuditJnalRembLoans { get; set; }
        public virtual DbSet<AuditOpCaisA> AuditOpCaisAs { get; set; }
        public virtual DbSet<AuditOpDiversA> AuditOpDiversAs { get; set; }
        public virtual DbSet<AuditPostLoan> AuditPostLoans { get; set; }
        public virtual DbSet<AuditProduct> AuditProducts { get; set; }
        public virtual DbSet<AuditProductTxn> AuditProductTxns { get; set; }
        public virtual DbSet<AuditServerStatu> AuditServerStatus { get; set; }
        public virtual DbSet<AuditStopPayment> AuditStopPayments { get; set; }
        public virtual DbSet<AuditVaultTxn> AuditVaultTxns { get; set; }
        public virtual DbSet<AuditVirPermanent> AuditVirPermanents { get; set; }
        public virtual DbSet<AuditVirSpont> AuditVirSponts { get; set; }
        public virtual DbSet<AuditVirSpontPer> AuditVirSpontPers { get; set; }
        public virtual DbSet<BILLETHISTTEMP> BILLETHISTTEMPs { get; set; }
        public virtual DbSet<BillingOption> BillingOptions { get; set; }
        public virtual DbSet<CautionSit> CautionSits { get; set; }
        public virtual DbSet<ChequeStock> ChequeStocks { get; set; }
        public virtual DbSet<Chequier> Chequiers { get; set; }
        public virtual DbSet<COBACHeader> COBACHeaders { get; set; }
        public virtual DbSet<Commande> Commandes { get; set; }
        public virtual DbSet<CommissionSm> CommissionSms { get; set; }
        public virtual DbSet<CpteCltCentral> CpteCltCentrals { get; set; }
        public virtual DbSet<CpteCltClose> CpteCltCloses { get; set; }
        public virtual DbSet<CpteCltHistb> CpteCltHistbs { get; set; }
        public virtual DbSet<CpteCltHistBBF> CpteCltHistBBFs { get; set; }
        public virtual DbSet<CpteCltHistRienB> CpteCltHistRienBs { get; set; }
        public virtual DbSet<CpteCltRienB> CpteCltRienBs { get; set; }
        public virtual DbSet<CpteCltSM> CpteCltSMS { get; set; }
        public virtual DbSet<CreDoc> CreDocs { get; set; }
        public virtual DbSet<CustomerRelationship> CustomerRelationships { get; set; }
        public virtual DbSet<DepotTermeHist> DepotTermeHists { get; set; }
        public virtual DbSet<Domiciliation> Domiciliations { get; set; }
        public virtual DbSet<EcritCptProv> EcritCptProvs { get; set; }
        public virtual DbSet<EMP_MODULE_MENU> EMP_MODULE_MENU { get; set; }
        public virtual DbSet<EmpPrivSet> EmpPrivSets { get; set; }
        public virtual DbSet<ExcludeProvision> ExcludeProvisions { get; set; }
        public virtual DbSet<FCashStock> FCashStocks { get; set; }
        public virtual DbSet<FCashVente> FCashVentes { get; set; }
        public virtual DbSet<FCashVente1> FCashVente1 { get; set; }
        public virtual DbSet<FCltTmpDeb> FCltTmpDebs { get; set; }
        public virtual DbSet<FCltTmpFin> FCltTmpFins { get; set; }
        public virtual DbSet<fcptgRienB> fcptgRienBs { get; set; }
        public virtual DbSet<FCRemb> FCRembs { get; set; }
        public virtual DbSet<FTableBalResultat> FTableBalResultats { get; set; }
        public virtual DbSet<GlHistRienB> GlHistRienBs { get; set; }
        public virtual DbSet<HistMp> HistMps { get; set; }
        public virtual DbSet<InteretReserv> InteretReservs { get; set; }
        public virtual DbSet<InteretReservBi> InteretReservBis { get; set; }
        public virtual DbSet<JnlInteretPerDay> JnlInteretPerDays { get; set; }
        public virtual DbSet<JudiciaryInstance> JudiciaryInstances { get; set; }
        public virtual DbSet<Jurisdiction> Jurisdictions { get; set; }
        public virtual DbSet<LegalOperation> LegalOperations { get; set; }
        public virtual DbSet<Litigation> Litigations { get; set; }
        public virtual DbSet<ManageCashier> ManageCashiers { get; set; }
        public virtual DbSet<Mouchard> Mouchards { get; set; }
        public virtual DbSet<MoucheSup> MoucheSups { get; set; }
        public virtual DbSet<MouchSec> MouchSecs { get; set; }
        public virtual DbSet<nomenposteOLD> nomenposteOLDs { get; set; }
        public virtual DbSet<OpCaisB> OpCaisBs { get; set; }
        public virtual DbSet<OpDiversABi> OpDiversABis { get; set; }
        public virtual DbSet<operationtype> operationtypes { get; set; }
        public virtual DbSet<optncounter> optncounters { get; set; }
        public virtual DbSet<PayrollAcct> PayrollAccts { get; set; }
        public virtual DbSet<Pay> Pays { get; set; }
        public virtual DbSet<PostHistory> PostHistories { get; set; }
        public virtual DbSet<ProfitabilityM> ProfitabilityMs { get; set; }
        public virtual DbSet<RemDoc> RemDocs { get; set; }
        public virtual DbSet<RepHeaderName> RepHeaderNames { get; set; }
        public virtual DbSet<REserveAcctInfo> REserveAcctInfoes { get; set; }
        public virtual DbSet<SaisieSolde> SaisieSoldes { get; set; }
        public virtual DbSet<SalEmp> SalEmps { get; set; }
        public virtual DbSet<tabCashOptnsReceiv> tabCashOptnsReceivs { get; set; }
        public virtual DbSet<tabCashOptnsSm> tabCashOptnsSms { get; set; }
        public virtual DbSet<TabClearingRate> TabClearingRates { get; set; }
        public virtual DbSet<tabcodegroupOLD> tabcodegroupOLDs { get; set; }
        public virtual DbSet<tabcoefccre> tabcoefccres { get; set; }
        public virtual DbSet<tabcoefliquidite> tabcoefliquidites { get; set; }
        public virtual DbSet<TabComWestern> TabComWesterns { get; set; }
        public virtual DbSet<TabConfigReportCobacOLD> TabConfigReportCobacOLDs { get; set; }
        public virtual DbSet<TabCpteAttente> TabCpteAttentes { get; set; }
        public virtual DbSet<tabCreditError> tabCreditErrors { get; set; }
        public virtual DbSet<TabCreditTMP> TabCreditTMPs { get; set; }
        public virtual DbSet<TabDifference> TabDifferences { get; set; }
        public virtual DbSet<TabdsdbRate> TabdsdbRates { get; set; }
        public virtual DbSet<TabEmergencyLoan> TabEmergencyLoans { get; set; }
        public virtual DbSet<tabEmpSalary> tabEmpSalaries { get; set; }
        public virtual DbSet<tabExemptBudget> tabExemptBudgets { get; set; }
        public virtual DbSet<tabexemptcustomeracct> tabexemptcustomeraccts { get; set; }
        public virtual DbSet<tabfondspatnet> tabfondspatnets { get; set; }
        public virtual DbSet<tabfondssol> tabfondssols { get; set; }
        public virtual DbSet<tabGLAcctExempt> tabGLAcctExempts { get; set; }
        public virtual DbSet<TabGrDec> TabGrDecs { get; set; }
        public virtual DbSet<Table_Archive> Table_Archive { get; set; }
        public virtual DbSet<TabLoanAttribute> TabLoanAttributes { get; set; }
        public virtual DbSet<TabLoanHandling> TabLoanHandlings { get; set; }
        public virtual DbSet<TabLoanInsurance> TabLoanInsurances { get; set; }
        public virtual DbSet<tabloaninterest> tabloaninterests { get; set; }
        public virtual DbSet<TabLoanStudyFee> TabLoanStudyFees { get; set; }
        public virtual DbSet<tabratcouvimmo> tabratcouvimmoes { get; set; }
        public virtual DbSet<tabratcouvrisk> tabratcouvrisks { get; set; }
        public virtual DbSet<tabratlignefin> tabratlignefins { get; set; }
        public virtual DbSet<tabreportOLD> tabreportOLDs { get; set; }
        public virtual DbSet<tabresultsconfig> tabresultsconfigs { get; set; }
        public virtual DbSet<TabRetourInterBr> TabRetourInterBrs { get; set; }
        public virtual DbSet<TabSalComp> TabSalComps { get; set; }
        public virtual DbSet<tabSumImpaye> tabSumImpayes { get; set; }
        public virtual DbSet<tabSumIntLoan> tabSumIntLoans { get; set; }
        public virtual DbSet<TabTransferRate> TabTransferRates { get; set; }
        public virtual DbSet<tabtreasuryconsult> tabtreasuryconsults { get; set; }
        public virtual DbSet<TCStock> TCStocks { get; set; }
        public virtual DbSet<TCSVente> TCSVentes { get; set; }
        public virtual DbSet<TempTabBadUnpaid> TempTabBadUnpaids { get; set; }
        public virtual DbSet<TmpDAteRange> TmpDAteRanges { get; set; }
        public virtual DbSet<TmpDormantToClose> TmpDormantToCloses { get; set; }
        public virtual DbSet<TmpStatementIncExp> TmpStatementIncExps { get; set; }
        public virtual DbSet<TransferState> TransferStates { get; set; }
        public virtual DbSet<TransfertVEComex> TransfertVEComexes { get; set; }
        public virtual DbSet<VaultTxnsTEMP> VaultTxnsTEMPs { get; set; }
        public virtual DbSet<VirPermanentHist> VirPermanentHists { get; set; }
        public virtual DbSet<VirRecuComex> VirRecuComexes { get; set; }
        public virtual DbSet<cipcb01> cipcb01 { get; set; }
        public virtual DbSet<cipcb03> cipcb03 { get; set; }
        public virtual DbSet<fibane01> fibane01 { get; set; }
        public virtual DbSet<fibane02> fibane02 { get; set; }
        public virtual DbSet<V_AuditBonCaisse> V_AuditBonCaisse { get; set; }
        public virtual DbSet<V_AuditClientBnk> V_AuditClientBnk { get; set; }
        public virtual DbSet<V_AuditContentieux> V_AuditContentieux { get; set; }
        public virtual DbSet<V_AuditCpteclt> V_AuditCpteclt { get; set; }
        public virtual DbSet<V_AuditCpteCltHist> V_AuditCpteCltHist { get; set; }
        public virtual DbSet<V_AuditCredit> V_AuditCredit { get; set; }
        public virtual DbSet<V_AuditDepotTerme> V_AuditDepotTerme { get; set; }
        public virtual DbSet<V_AuditGlHist> V_AuditGlHist { get; set; }
        public virtual DbSet<V_AuditHistoCaisse> V_AuditHistoCaisse { get; set; }
        public virtual DbSet<V_AuditImpayes> V_AuditImpayes { get; set; }
        public virtual DbSet<V_AuditJnalRembLoan> V_AuditJnalRembLoan { get; set; }
    
        [DbFunction("BankingEntities", "CalCulSolde")]
        public virtual IQueryable<CalCulSolde_Result> CalCulSolde(string cpteJumelle)
        {
            var cpteJumelleParameter = cpteJumelle != null ?
                new ObjectParameter("CpteJumelle", cpteJumelle) :
                new ObjectParameter("CpteJumelle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CalCulSolde_Result>("[BankingEntities].[CalCulSolde](@CpteJumelle)", cpteJumelleParameter);
        }
    
        [DbFunction("BankingEntities", "CalCulSoldeAgio")]
        public virtual IQueryable<CalCulSoldeAgio_Result> CalCulSoldeAgio(string cpteJumelle, Nullable<System.DateTime> dateOP, Nullable<System.DateTime> serverdate)
        {
            var cpteJumelleParameter = cpteJumelle != null ?
                new ObjectParameter("CpteJumelle", cpteJumelle) :
                new ObjectParameter("CpteJumelle", typeof(string));
    
            var dateOPParameter = dateOP.HasValue ?
                new ObjectParameter("dateOP", dateOP) :
                new ObjectParameter("dateOP", typeof(System.DateTime));
    
            var serverdateParameter = serverdate.HasValue ?
                new ObjectParameter("Serverdate", serverdate) :
                new ObjectParameter("Serverdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CalCulSoldeAgio_Result>("[BankingEntities].[CalCulSoldeAgio](@CpteJumelle, @dateOP, @Serverdate)", cpteJumelleParameter, dateOPParameter, serverdateParameter);
        }
    
        [DbFunction("BankingEntities", "CalCulSoldeWithoutValidate")]
        public virtual IQueryable<CalCulSoldeWithoutValidate_Result> CalCulSoldeWithoutValidate(string cpteJumelle)
        {
            var cpteJumelleParameter = cpteJumelle != null ?
                new ObjectParameter("CpteJumelle", cpteJumelle) :
                new ObjectParameter("CpteJumelle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CalCulSoldeWithoutValidate_Result>("[BankingEntities].[CalCulSoldeWithoutValidate](@CpteJumelle)", cpteJumelleParameter);
        }
    
        [DbFunction("BankingEntities", "ChargeBranch")]
        public virtual IQueryable<ChargeBranch_Result> ChargeBranch(string matricule)
        {
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ChargeBranch_Result>("[BankingEntities].[ChargeBranch](@matricule)", matriculeParameter);
        }
    
        [DbFunction("BankingEntities", "ChargeBranchBis")]
        public virtual IQueryable<ChargeBranchBis_Result> ChargeBranchBis(string matricule)
        {
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ChargeBranchBis_Result>("[BankingEntities].[ChargeBranchBis](@matricule)", matriculeParameter);
        }
    }
}
