//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class BilletHist
    {
        public string Agence { get; set; }
        public string Caisse { get; set; }
        public string devise { get; set; }
        public Nullable<System.DateTime> DateOperation { get; set; }
        public string TypeBilletP { get; set; }
        public short Coupure { get; set; }
        public Nullable<double> Quantite { get; set; }
        public string globex { get; set; }
    }
}
