//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingOptiono
    {
        public string BillingOptionId { get; set; }
        public string BillingOptionName { get; set; }
        public Nullable<double> BasePeriodicRate { get; set; }
        public Nullable<double> MinCostPerSMS { get; set; }
        public Nullable<double> MaximumSMSQty { get; set; }
    }
}
