//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonCaisse
    {
        public string Agence { get; set; }
        public int Serie { get; set; }
        public string Client { get; set; }
        public string Denomination { get; set; }
        public string CpteJumelleCC { get; set; }
        public short CatCpte { get; set; }
        public string CpteJumelleCpteTerm { get; set; }
        public string CpteGL { get; set; }
        public string CleCpte { get; set; }
        public double Montant { get; set; }
        public Nullable<double> TauxInt { get; set; }
        public Nullable<double> TxTVA { get; set; }
        public Nullable<double> TxTPRCM { get; set; }
        public Nullable<System.DateTime> DateContrat { get; set; }
        public Nullable<System.DateTime> DatePriseEffet { get; set; }
        public short Duree { get; set; }
        public Nullable<System.DateTime> DateDernCalInt { get; set; }
        public Nullable<double> CumulIntMensuel { get; set; }
        public Nullable<double> InteretCouru { get; set; }
        public Nullable<double> InteretMois { get; set; }
        public string ModePayInt { get; set; }
        public Nullable<System.DateTime> DateExpiration { get; set; }
        public string NumeroContrat { get; set; }
        public Nullable<short> NbreSign { get; set; }
        public Nullable<System.DateTime> DateCptaTerm { get; set; }
        public Nullable<System.DateTime> DateCptaInteret { get; set; }
        public Nullable<System.DateTime> DateCptaRemb { get; set; }
        public string Statut { get; set; }
        public string Renouvellement { get; set; }
        public Nullable<System.DateTime> DateRemb { get; set; }
        public Nullable<double> TauxPenalite { get; set; }
        public Nullable<double> MtPenalite { get; set; }
        public Nullable<short> NbreReconduit { get; set; }
        public Nullable<System.DateTime> DateDerniereRecond { get; set; }
        public string LibAgence { get; set; }
        public string LibCatCpte { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Employe { get; set; }
        public string LibEmploye { get; set; }
        public Nullable<System.DateTime> DateVals { get; set; }
        public Nullable<System.DateTime> DateCptaMens { get; set; }
        public string CaisseCpte { get; set; }
        public string RefCaisse { get; set; }
        public Nullable<double> TotalCapitalise { get; set; }
        public string CapitalInt { get; set; }
        public string LibCpteGl { get; set; }
        public string titrepaye { get; set; }
        public Nullable<System.DateTime> datepymttitre { get; set; }
        public Nullable<double> MtInteret { get; set; }
        public string TxnNo { get; set; }
        public Nullable<double> SupInt { get; set; }
        public Nullable<double> interetdu { get; set; }
        public Nullable<System.DateTime> DateTransfert { get; set; }
        public string CalFrequency { get; set; }
        public Nullable<int> DureeCourue { get; set; }
        public Nullable<double> currentintamount { get; set; }
        public string StatutMarch { get; set; }
        public string StatutJune { get; set; }
        public string StatutSeptember { get; set; }
        public string StatutDecember { get; set; }
        public Nullable<double> Tprcm { get; set; }
    }
}
