//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caisse
    {
        public string CodeCaisse { get; set; }
        public string devise { get; set; }
        public string Libelle { get; set; }
        public Nullable<double> MontantDep { get; set; }
        public Nullable<double> DebitJour { get; set; }
        public Nullable<double> CreditJour { get; set; }
        public string Compte { get; set; }
        public Nullable<System.DateTime> DateJour { get; set; }
        public string Employe { get; set; }
        public Nullable<double> Solde { get; set; }
        public string Tellerstatus { get; set; }
        public Nullable<System.DateTime> Datelastopen { get; set; }
        public Nullable<System.DateTime> Datelastadjust { get; set; }
        public Nullable<System.DateTime> Datelastclose { get; set; }
        public string agence { get; set; }
        public string TellerType { get; set; }
    }
}
