//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatCpte
    {
        public short CatCpte1 { get; set; }
        public string Designation { get; set; }
        public string DesignAnglais { get; set; }
        public string CpteColClt { get; set; }
        public string CleColClt { get; set; }
        public string LibCpteColClt { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<short> Employe { get; set; }
        public string NomEmploye { get; set; }
        public Nullable<System.DateTime> DateTransfert { get; set; }
        public string Opdiver { get; set; }
        public Nullable<double> TxIntCr { get; set; }
        public Nullable<double> TxIntdb { get; set; }
        public Nullable<double> SMinBal { get; set; }
        public Nullable<double> MtFTC { get; set; }
        public Nullable<double> AcctOpenCharge { get; set; }
        public Nullable<double> ChequeCharges { get; set; }
        public Nullable<double> CounterChequeCharge { get; set; }
        public Nullable<double> TxComMvt { get; set; }
        public Nullable<double> TxComDec { get; set; }
        public Nullable<double> TPRCM { get; set; }
        public Nullable<double> FraisExceptionnel { get; set; }
        public Nullable<double> ManagementCharge { get; set; }
        public Nullable<double> ODFormFee { get; set; }
        public Nullable<double> TxTVA { get; set; }
        public string visibCredit { get; set; }
        public string visdep { get; set; }
        public string VisRet { get; set; }
        public string vispersocheck { get; set; }
        public string viscracc { get; set; }
        public string calint { get; set; }
        public string Fraisexceptype { get; set; }
        public string Blockdatetype { get; set; }
        public string caldatevaltype { get; set; }
        public string cpteinteret { get; set; }
        public string clecpteinteret { get; set; }
        public string libcpteinteret { get; set; }
        public string libcpteimpaye { get; set; }
        public string cpteimpaye { get; set; }
        public string clecpteimpaye { get; set; }
        public string decouvert { get; set; }
        public string abonementsms { get; set; }
        public string DebitInterestMethod { get; set; }
        public string cpteContentieux { get; set; }
        public string clecpteContentieux { get; set; }
        public string libcpteContentieux { get; set; }
    }
}
