//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public string CatClient { get; set; }
        public string CustomerType { get; set; }
        public string LibCatClient { get; set; }
        public string Apparente { get; set; }
    }
}
