//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class CautionAval
    {
        public short Agence { get; set; }
        public string MatClient { get; set; }
        public int NumeroEngag { get; set; }
        public string NomPrenom { get; set; }
        public short CatCpte { get; set; }
        public short SubCpte { get; set; }
        public string LetCle { get; set; }
        public string CpteIndCaution { get; set; }
        public string LibCatCpte { get; set; }
        public string CodeCAval { get; set; }
        public Nullable<System.DateTime> DateEmission { get; set; }
        public Nullable<System.DateTime> DateEcheance { get; set; }
        public string PeriodCalCom { get; set; }
        public double MontantCaution { get; set; }
        public string CleCpteGLC { get; set; }
        public string CpteGLCaution { get; set; }
        public string LibCpteGLCaution { get; set; }
        public string CleCpteGLProv { get; set; }
        public string CpteGLProvCaution { get; set; }
        public string LibCpteGLProvCaution { get; set; }
        public string CleCpteCaution { get; set; }
        public string CpteCaution { get; set; }
        public string LibCpteCaution { get; set; }
        public Nullable<System.DateTime> DDerPerCom { get; set; }
        public Nullable<System.DateTime> DProPerCom { get; set; }
        public Nullable<System.DateTime> DMainL { get; set; }
        public string TypeML { get; set; }
        public Nullable<double> CumMLC { get; set; }
        public Nullable<System.DateTime> DSortiePFE { get; set; }
        public Nullable<double> TxComm { get; set; }
        public Nullable<double> MtComm { get; set; }
        public Nullable<double> FraisDossier { get; set; }
        public Nullable<double> TauxTVA { get; set; }
        public Nullable<double> MtTVA { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string LibAgence { get; set; }
        public Nullable<short> Employe { get; set; }
        public string LibEmploye { get; set; }
        public Nullable<short> Gestionnaire { get; set; }
        public string LibGest { get; set; }
        public Nullable<short> NumEcheance { get; set; }
        public string CompteTVA { get; set; }
        public string CleCpteTVA { get; set; }
        public string LibCompteTVA { get; set; }
        public string CompteFraisDossier { get; set; }
        public string CleCpteFrDoss { get; set; }
        public string LibCompteFraisDossier { get; set; }
        public string CompteCom { get; set; }
        public string CleCpteCom { get; set; }
        public string LibCompteCom { get; set; }
        public string CpteColClt { get; set; }
        public string CleColClt { get; set; }
        public string LibCpteColClt { get; set; }
        public Nullable<double> PDL { get; set; }
        public Nullable<double> MontantProvision { get; set; }
        public string RefInterne { get; set; }
        public string CpteIndProvision { get; set; }
        public Nullable<System.DateTime> DateCptaCaution { get; set; }
        public Nullable<double> MtComACptab { get; set; }
        public Nullable<System.DateTime> DateCalCommis { get; set; }
        public Nullable<System.DateTime> DateCptaMainLev { get; set; }
    }
}
