//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheqTrait
    {
        public string Agence { get; set; }
        public Nullable<System.DateTime> DateOP { get; set; }
        public string CptejumelleCC { get; set; }
        public string Tracer { get; set; }
        public string Numero { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Denomination { get; set; }
        public decimal Serie { get; set; }
        public string SerieChequier { get; set; }
    }
}
