//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chequier
    {
        public string Cptejumellecc { get; set; }
        public string Denomination { get; set; }
        public decimal NbreCheq { get; set; }
        public string CheckKey { get; set; }
        public string Dserie { get; set; }
        public string Fserie { get; set; }
        public string TypeCheque { get; set; }
        public Nullable<System.DateTime> DatePers { get; set; }
        public Nullable<System.DateTime> DateSuspension { get; set; }
        public Nullable<System.DateTime> DateLeveSuspension { get; set; }
        public string Suspension { get; set; }
    }
}
