//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeStock
    {
        public int NumCmde { get; set; }
        public int Agence { get; set; }
        public string LibAgence { get; set; }
        public string CpteJumelleCC { get; set; }
        public string Denomination { get; set; }
        public string CheckKey { get; set; }
        public string DSerie { get; set; }
        public string FSerie { get; set; }
        public string Etat { get; set; }
        public Nullable<int> NmbreCheque { get; set; }
        public Nullable<System.DateTime> DatePers { get; set; }
    }
}
