//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class cipcb01
    {
        public string nature_dec { get; set; }
        public string code_etab { get; set; }
        public string code_vil { get; set; }
        public string sigle_etab { get; set; }
        public string code_age { get; set; }
        public string nom_age { get; set; }
        public string num_cpte { get; set; }
        public string date_ouv { get; set; }
        public string typ_cpte { get; set; }
        public double mon_ouv { get; set; }
        public string ni_titu { get; set; }
        public string statut_int { get; set; }
        public string typ_pers { get; set; }
        public string forme_jur { get; set; }
        public string raison_so { get; set; }
        public string date_crea { get; set; }
        public string adresse { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string boite_p { get; set; }
        public string num_tel { get; set; }
        public string email { get; set; }
        public string date_nais { get; set; }
        public string lieu_nais { get; set; }
        public string rccm { get; set; }
        public string devise_cpte { get; set; }
        public int statut_res { get; set; }
    }
}
