//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class cipcb03
    {
        public string nature_dec { get; set; }
        public string code_etab { get; set; }
        public string code_vil { get; set; }
        public string sigle_etab { get; set; }
        public string code_age { get; set; }
        public string num_cpte { get; set; }
        public string typ_cpte { get; set; }
        public string date_fer { get; set; }
        public string code_motif { get; set; }
        public Nullable<int> date_rest_chequier { get; set; }
        public Nullable<int> date_rest_carte { get; set; }
    }
}
