//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public string Agence { get; set; }
        public string LibAgence { get; set; }
        public int NumCmde { get; set; }
        public System.DateTime DateCmde { get; set; }
        public string NumImprimeur { get; set; }
        public string CheckKey { get; set; }
        public int NmbreCheque { get; set; }
        public string DSerie { get; set; }
        public string FSerie { get; set; }
    }
}
