//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public string Agence { get; set; }
        public string CompanyName { get; set; }
        public string CompanyDesc { get; set; }
        public string Employe { get; set; }
        public string cptegl { get; set; }
        public string operationtype { get; set; }
        public string TreatmentType { get; set; }
        public string cpteglpay { get; set; }
        public string cpteglint { get; set; }
        public string cpteglln { get; set; }
    }
}
