//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigTypeLoan
    {
        public string LoanType { get; set; }
        public string LoanTypeDescription { get; set; }
        public Nullable<int> PeriodDebut { get; set; }
        public Nullable<int> PeriodFin { get; set; }
        public string Periodicite { get; set; }
        public Nullable<double> LoanBranchLimit { get; set; }
    }
}
