//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrespTable
    {
        public string devise { get; set; }
        public string libdevise { get; set; }
        public string cptegl { get; set; }
        public string clecptegl { get; set; }
        public string libcptegl { get; set; }
        public string cpteglapprov { get; set; }
        public string clecpteglapprov { get; set; }
        public string libcpteglapprov { get; set; }
        public int series { get; set; }
    }
}
