//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpteCltRienB
    {
        public int Agence { get; set; }
        public int Client { get; set; }
        public string CpteJumelle { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public string LibClient { get; set; }
        public short CatCpte { get; set; }
        public string LibCatCpte { get; set; }
        public short Subcpte { get; set; }
        public string LetCle { get; set; }
        public string Devise { get; set; }
        public Nullable<double> LigneDec { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public string CpteCol { get; set; }
        public string CleCol { get; set; }
        public Nullable<System.DateTime> DateOuverture { get; set; }
        public Nullable<int> Gestionnaire { get; set; }
        public string Statut { get; set; }
        public Nullable<System.DateTime> DateEff { get; set; }
        public Nullable<short> TotalSignature { get; set; }
        public Nullable<short> SignatureVal { get; set; }
        public string Fusion { get; set; }
        public string LibAgence { get; set; }
        public string LibDevise { get; set; }
        public string LibCpteCol { get; set; }
        public string LibGestionnaire { get; set; }
        public string CpteOvation { get; set; }
        public Nullable<double> TxIntDb { get; set; }
        public Nullable<double> TxIntCr { get; set; }
        public bool ExoTDC { get; set; }
        public bool ExoTVA { get; set; }
        public bool ExoTPRCM { get; set; }
        public bool ExoFTC { get; set; }
        public Nullable<double> TxComDec { get; set; }
        public Nullable<double> TxComMvt { get; set; }
        public Nullable<double> TxTVA { get; set; }
        public Nullable<int> MtFTC { get; set; }
        public Nullable<int> Employe { get; set; }
        public string Nomemploye { get; set; }
        public string CpteIndAgioRes { get; set; }
        public string CpteGenAgioRes { get; set; }
        public string CleGenAgioRes { get; set; }
        public string LibCpteGenAgioRes { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> Expirationlignedec { get; set; }
        public bool CRBlocage { get; set; }
        public bool DBBlocage { get; set; }
        public Nullable<double> Cantonnement { get; set; }
        public Nullable<System.DateTime> CRBlockDate { get; set; }
        public Nullable<System.DateTime> DBBlockDate { get; set; }
        public Nullable<System.DateTime> DateDernierMvtDB { get; set; }
        public Nullable<System.DateTime> DateDernierMvtCR { get; set; }
        public Nullable<System.DateTime> StopIntDate { get; set; }
        public bool StopInt { get; set; }
        public bool ReservedInt { get; set; }
        public Nullable<System.DateTime> DateDeclaration { get; set; }
        public Nullable<System.DateTime> datetransf { get; set; }
        public bool controlacces { get; set; }
    }
}
