//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpteCltSM
    {
        public int Agence { get; set; }
        public string CpteJumelle { get; set; }
        public string Denomination { get; set; }
        public string MotDePasse { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> Solde { get; set; }
        public Nullable<System.DateTime> DateExpiration { get; set; }
        public Nullable<double> AncienIndex { get; set; }
        public Nullable<double> NVeauIndex { get; set; }
        public Nullable<System.DateTime> DateFacturation { get; set; }
    }
}
