//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataImport
    {
        public decimal pk { get; set; }
        public string AccountNum { get; set; }
        public string Denomination { get; set; }
        public System.DateTime DateSaisie { get; set; }
        public double Amount { get; set; }
        public string Employe { get; set; }
        public string statut { get; set; }
        public string sens { get; set; }
        public string Glacc { get; set; }
    }
}
