//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepotTermeHist
    {
        public Nullable<short> Agence { get; set; }
        public Nullable<double> SerieTP { get; set; }
        public int Serie { get; set; }
        public string CpteJumelleCC { get; set; }
        public string Denomination { get; set; }
        public Nullable<short> CatCpte { get; set; }
        public string CpteJumelleCpteTerm { get; set; }
        public string CpteGL { get; set; }
        public string CleCpte { get; set; }
        public string LibCpteGl { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<double> TauxInt { get; set; }
        public Nullable<double> TxTVA { get; set; }
        public Nullable<double> TxTPRCM { get; set; }
        public Nullable<System.DateTime> DateContrat { get; set; }
        public Nullable<System.DateTime> DatePriseEffet { get; set; }
        public Nullable<short> Duree { get; set; }
        public Nullable<double> CumulIntMensuel { get; set; }
        public string ModePayInt { get; set; }
        public Nullable<System.DateTime> DateExpiration { get; set; }
        public string NumeroContrat { get; set; }
        public Nullable<short> NbreSign { get; set; }
        public Nullable<System.DateTime> DateCptaTerm { get; set; }
        public Nullable<System.DateTime> DateCptaInteret { get; set; }
        public Nullable<System.DateTime> DateCptaRemb { get; set; }
        public string Statut { get; set; }
        public Nullable<short> NbreReconduit { get; set; }
        public Nullable<System.DateTime> DateDerniereRecond { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
    }
}
