//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepRetGeneralBi
    {
        public string Agence { get; set; }
        public string CpteJumelle { get; set; }
        public Nullable<int> CatCpte { get; set; }
        public string LibCatCpte { get; set; }
        public string Employe { get; set; }
        public string Description { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<double> Int { get; set; }
        public Nullable<double> Pen { get; set; }
        public Nullable<double> Solde { get; set; }
        public decimal Auto { get; set; }
        public string txno { get; set; }
        public Nullable<double> type { get; set; }
        public Nullable<double> vat { get; set; }
    }
}
