//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcritCptableBi
    {
        public string Agence { get; set; }
        public string Devise { get; set; }
        public string Journal { get; set; }
        public int Folio { get; set; }
        public System.DateTime DateOperation { get; set; }
        public decimal Ligne { get; set; }
        public string Compte { get; set; }
        public string CodeLibelle { get; set; }
        public string Libelle { get; set; }
        public string RefEcrit { get; set; }
        public string RefOperation { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<System.DateTime> DateValeur { get; set; }
        public Nullable<System.DateTime> DateEch { get; set; }
        public string CodeMaj { get; set; }
        public string CodeEmpl { get; set; }
        public Nullable<System.DateTime> DateSaisie { get; set; }
        public string CpteClt { get; set; }
        public string Description { get; set; }
        public string TxnNo { get; set; }
        public string codeoperation { get; set; }
        public string libelleoperation { get; set; }
        public string BENEFICIARY { get; set; }
        public string representative { get; set; }
        public string achivedata { get; set; }
    }
}
