//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmetteurTCSComex
    {
        public string Emetteur { get; set; }
        public string Denomination { get; set; }
        public string Adresse { get; set; }
        public string Pays { get; set; }
        public string Ville { get; set; }
        public string Compte { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
    }
}
