//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE_MODULE
    {
        public string MATRICULE { get; set; }
        public string MODULENAME { get; set; }
        public Nullable<System.DateTime> DATEAUTORISEMOD { get; set; }
        public string Employe { get; set; }
        public string MENUDESC { get; set; }
    }
}
