//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncoursCustomer
    {
        public string Client { get; set; }
        public string Denomination { get; set; }
        public string CpteCol { get; set; }
        public string CpteJumelle { get; set; }
        public Nullable<double> AmountDebutDb { get; set; }
        public Nullable<double> AmountFinDb { get; set; }
        public Nullable<double> AmountDebutCr { get; set; }
        public Nullable<double> AmountFinCr { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string Agence { get; set; }
        public string devise { get; set; }
        public string CodeGroupe { get; set; }
        public string LibelleGroupe { get; set; }
        public string CodeDetail { get; set; }
        public string LibelleDetail { get; set; }
        public string Etat { get; set; }
        public string libelleetat { get; set; }
        public string Matricule { get; set; }
    }
}
