//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class EODProcess
    {
        public string code { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateEOD { get; set; }
        public Nullable<System.DateTime> DateOuverture { get; set; }
        public string Applicable { get; set; }
        public string LibelleFr { get; set; }
    }
}
