//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcludeProvision
    {
        public string Etat { get; set; }
        public string CodePoste { get; set; }
        public string groupcode { get; set; }
        public string CpteGl { get; set; }
        public string CpteGlAExclu { get; set; }
        public string CpteGlProvision { get; set; }
        public decimal Serie { get; set; }
    }
}
