//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCashVente
    {
        public Nullable<short> Agence { get; set; }
        public string Devise { get; set; }
        public int Serie { get; set; }
        public string Emetteur { get; set; }
        public string Ref { get; set; }
        public string CpteJumelleCC { get; set; }
        public string Denomination { get; set; }
        public Nullable<System.DateTime> DateOuverture { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<double> Cours { get; set; }
        public string CodeTraitement { get; set; }
        public Nullable<System.DateTime> DateTraitement { get; set; }
        public string LibDevise { get; set; }
        public string CpteGL { get; set; }
        public string CleCpte { get; set; }
        public string LibCpteGl { get; set; }
        public Nullable<System.DateTime> DateVente { get; set; }
        public Nullable<System.DateTime> DateCptaVente { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string AutDecl { get; set; }
        public string Description { get; set; }
        public string TypeAcquisition { get; set; }
        public string LibAgence { get; set; }
        public string LibEmetteur { get; set; }
    }
}
