//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCltTmpDeb
    {
        public int agence { get; set; }
        public string devise { get; set; }
        public string cptecol { get; set; }
        public string CpteJumelle { get; set; }
        public Nullable<double> SDebit { get; set; }
        public Nullable<double> SCredit { get; set; }
    }
}
