//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class fclttmp
    {
        public string Agence { get; set; }
        public string Devise { get; set; }
        public string CpteJumelle { get; set; }
        public Nullable<double> DebitRep { get; set; }
        public Nullable<double> CreditRep { get; set; }
        public Nullable<double> DebitMvt { get; set; }
        public Nullable<double> CreditMvt { get; set; }
        public Nullable<double> DebitCum { get; set; }
        public Nullable<double> CreditCum { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public string CpteCol { get; set; }
        public string LibAgence { get; set; }
        public string Denomination { get; set; }
        public string Cle { get; set; }
        public string LibCpteCol { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string catclient { get; set; }
        public string agenteco { get; set; }
        public string matricule { get; set; }
        public string Client { get; set; }
        public string ProductType { get; set; }
        public decimal pk { get; set; }
        public string qualite { get; set; }
    }
}
