//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fcptg99
    {
        public string Agence { get; set; }
        public string Devise { get; set; }
        public string Compte { get; set; }
        public string Cle { get; set; }
        public string Libelle { get; set; }
        public string LibAgence { get; set; }
        public string CGType { get; set; }
        public Nullable<double> DebitRep { get; set; }
        public Nullable<double> CreditRep { get; set; }
        public Nullable<double> DebitMvt { get; set; }
        public Nullable<double> CreditMvt { get; set; }
        public Nullable<double> DebitCum { get; set; }
        public Nullable<double> CreditCum { get; set; }
        public Nullable<double> SoldeDebit { get; set; }
        public Nullable<double> SoldeCredit { get; set; }
        public string cgnumas { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<double> CreditCFA { get; set; }
        public Nullable<double> DebitCFA { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string Annee { get; set; }
        public string Employe { get; set; }
    }
}
