//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class fcptgRienB
    {
        public int agcod { get; set; }
        public string devcod { get; set; }
        public string cgnum { get; set; }
        public string cglc { get; set; }
        public string cglibf { get; set; }
        public string cgliba { get; set; }
        public string cgcol { get; set; }
        public string cgden { get; set; }
        public string cgtype { get; set; }
        public string cgstatut { get; set; }
        public Nullable<double> cgdbo { get; set; }
        public Nullable<double> cgcro { get; set; }
        public Nullable<double> cgdbm { get; set; }
        public Nullable<double> cgcrm { get; set; }
        public Nullable<double> cgdbe { get; set; }
        public Nullable<double> cgcre { get; set; }
        public string cgnumas { get; set; }
        public Nullable<System.DateTime> cgdatcr { get; set; }
        public string cgliben { get; set; }
        public string cgvent { get; set; }
        public Nullable<System.DateTime> datetransf { get; set; }
    }
}
