//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class FcptgTmp
    {
        public string Agence { get; set; }
        public string Devise { get; set; }
        public string Cle { get; set; }
        public string Libelle { get; set; }
        public string LibAgence { get; set; }
        public string CGType { get; set; }
        public Nullable<double> SoldePeriod { get; set; }
        public Nullable<double> SoldeCumul { get; set; }
        public string cgnumas { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Compte { get; set; }
        public string Employe { get; set; }
        public Nullable<double> ResultatPeriod { get; set; }
        public Nullable<double> ResultatCumul { get; set; }
    }
}
