//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class fcptg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fcptg()
        {
            this.CpteClts = new HashSet<CpteClt>();
            this.CpteCltHists = new HashSet<CpteCltHist>();
            this.CpteCltHistArches = new HashSet<CpteCltHistArch>();
            this.GlHists = new HashSet<GlHist>();
            this.GlHistArches = new HashSet<GlHistArch>();
        }
    
        public string devcod { get; set; }
        public string cgnum { get; set; }
        public string cglc { get; set; }
        public string cglibf { get; set; }
        public string cgtype { get; set; }
        public Nullable<System.DateTime> cgdatcr { get; set; }
        public string Employe { get; set; }
        public string Cgsens { get; set; }
        public string Cgstatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CpteClt> CpteClts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CpteCltHist> CpteCltHists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CpteCltHistArch> CpteCltHistArches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlHist> GlHists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlHistArch> GlHistArches { get; set; }
    }
}
