//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class fibane02
    {
        public string nature_dec { get; set; }
        public string debut_periode { get; set; }
        public string fin_periode { get; set; }
        public string type_periode { get; set; }
        public string code_etab { get; set; }
        public string code_age { get; set; }
        public string num_cpte { get; set; }
        public int creance_immo { get; set; }
        public int loyer_mob_inf_3 { get; set; }
        public int loyer_mob_achat_inf_3 { get; set; }
        public Nullable<double> credit_non_mob_inf3 { get; set; }
        public int loyer_imob_inf_6 { get; set; }
        public int credi_bail_imob_inf6 { get; set; }
        public int autre_credit_imob_inf6 { get; set; }
        public int concours_dech_plus3 { get; set; }
        public int concours_ech_imp_plus3_6 { get; set; }
        public int compte_ss_mvt_crediteur_3 { get; set; }
        public Nullable<double> contentieux { get; set; }
        public int loyers_echus { get; set; }
    }
}
