//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTableLiability
    {
        public string Agence { get; set; }
        public string LibAgence { get; set; }
        public string Devise { get; set; }
        public string CodeGroupe { get; set; }
        public string LibelleGroupe { get; set; }
        public string CodeDetail { get; set; }
        public string LibelleDetail { get; set; }
        public Nullable<double> GrossAmount1 { get; set; }
        public Nullable<double> GrossAmount2 { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string Employe { get; set; }
        public decimal Serie { get; set; }
    }
}
