//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralTrxnBi
    {
        public string Agence { get; set; }
        public string Cpte { get; set; }
        public string LibCatCpte { get; set; }
        public string NomCompte { get; set; }
        public string Employe { get; set; }
        public string Description { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public decimal Auto { get; set; }
        public Nullable<double> type { get; set; }
        public Nullable<System.DateTime> opdate { get; set; }
        public string Txnno { get; set; }
        public string CONTRACTNUMBER { get; set; }
        public Nullable<double> TotInt { get; set; }
        public Nullable<double> Int { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<double> Pen { get; set; }
    }
}
