//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlHist
    {
        public string Agence { get; set; }
        public string Devise { get; set; }
        public string Compte { get; set; }
        public System.DateTime DateOperation { get; set; }
        public string Journal { get; set; }
        public int Folio { get; set; }
        public decimal Ligne { get; set; }
        public decimal NumEcrit { get; set; }
        public string CodeOperation { get; set; }
        public string LibelleOperation { get; set; }
        public string RefEcrit { get; set; }
        public string RefOperation { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateValeur { get; set; }
        public Nullable<System.DateTime> DateMaj { get; set; }
        public string CodeEmpl { get; set; }
        public Nullable<System.DateTime> DateSaisie { get; set; }
        public Nullable<int> Piece { get; set; }
        public string CpteJumelle { get; set; }
        public string TxnNo { get; set; }
        public string numpiece { get; set; }
        public string StateCumDateOp { get; set; }
        public string SateCumDateVal { get; set; }
        public string BENEFICIARY { get; set; }
        public string representative { get; set; }
        public string achivedata { get; set; }
    
        public virtual fcptg fcptg { get; set; }
    }
}
