//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistMp
    {
        public string Matricule { get; set; }
        public int Serie { get; set; }
        public string AncienMP { get; set; }
        public Nullable<System.DateTime> DateAttrib { get; set; }
        public Nullable<System.DateTime> DateChang { get; set; }
        public string LibEmploye { get; set; }
        public string Employe { get; set; }
        public string NomEmploye { get; set; }
    }
}
