//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Immo
    {
        public string Agence { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> DateAcquisition { get; set; }
        public string Designation { get; set; }
        public string CpteImmob { get; set; }
        public string ServiceAffectation { get; set; }
        public string LibService { get; set; }
        public Nullable<double> MontantInitial { get; set; }
        public Nullable<double> DureeIm { get; set; }
        public Nullable<double> TauxAmortissement { get; set; }
        public Nullable<double> AmortCummule { get; set; }
        public Nullable<double> ValeurResiduelle { get; set; }
        public Nullable<double> ValeurCession { get; set; }
        public string CpteAmortissement { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
        public string MotifSortie { get; set; }
        public Nullable<short> DureeGarantie { get; set; }
        public Nullable<double> AmortCalPeriode { get; set; }
        public Nullable<System.DateTime> DateDernCalAm { get; set; }
        public Nullable<System.DateTime> DateCptabAcq { get; set; }
        public Nullable<System.DateTime> DateCptabAmort { get; set; }
        public string Fournisseur { get; set; }
        public string CleTiers { get; set; }
        public string LibFournisseur { get; set; }
        public string TypeAcq { get; set; }
        public string RefFacture { get; set; }
        public Nullable<System.DateTime> DateProvCal { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string CodeType { get; set; }
        public string CodeLocal { get; set; }
        public Nullable<System.DateTime> DateMiseService { get; set; }
        public Nullable<double> Addition { get; set; }
        public string periodicitecompta { get; set; }
        public string RefTransaction { get; set; }
        public string PeriodiciteAmort { get; set; }
        public Nullable<int> monthnumber { get; set; }
        public string StatusAcq { get; set; }
        public string CpteDepreciation { get; set; }
        public Nullable<System.DateTime> DateInitCalcul { get; set; }
    }
}
