//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class InComeSM
    {
        public decimal InComesmsid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string SMSTransText { get; set; }
        public string PhoneNumber { get; set; }
        public string Flag { get; set; }
    }
}
