//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indisponible
    {
        public int Agence { get; set; }
        public string Devise { get; set; }
        public string CpteJumelle { get; set; }
        public Nullable<System.DateTime> DateOperation { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public System.DateTime DateSaisie { get; set; }
        public int Serie { get; set; }
        public Nullable<int> Employe { get; set; }
        public string LibEmploye { get; set; }
    }
}
