//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Institution()
        {
            this.agences = new HashSet<agence>();
        }
    
        public string CobacID { get; set; }
        public string motto { get; set; }
        public string publicite { get; set; }
        public string institution1 { get; set; }
        public string Typesociete { get; set; }
        public string CompanyAbbreviation { get; set; }
        public string Sauvegarde { get; set; }
        public string PathLogo { get; set; }
        public Nullable<int> SizeLogo { get; set; }
        public byte[] Logo { get; set; }
        public string PhotoName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agence> agences { get; set; }
    }
}
