//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class InteretReservBi
    {
        public string Agence { get; set; }
        public string CpteJumAgioRes { get; set; }
        public string CpteJumelle { get; set; }
        public Nullable<System.DateTime> DateIntDebut { get; set; }
        public Nullable<System.DateTime> DateIntFin { get; set; }
        public Nullable<double> Montant { get; set; }
        public string TypeOp { get; set; }
        public string DenoMination { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> DateOperation { get; set; }
        public Nullable<System.DateTime> DateReprise { get; set; }
        public string TxnNo { get; set; }
        public decimal serie { get; set; }
        public string Description { get; set; }
        public string CpteJumPrinc { get; set; }
    }
}
