//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class JnlInteret
    {
        public string Agence { get; set; }
        public string Client { get; set; }
        public Nullable<short> CatCpte { get; set; }
        public Nullable<short> Subcpte { get; set; }
        public string LetCle { get; set; }
        public string CpteJumelle { get; set; }
        public Nullable<System.DateTime> DateIntDebut { get; set; }
        public Nullable<System.DateTime> DateIntFin { get; set; }
        public Nullable<double> IntDb { get; set; }
        public Nullable<double> IntCr { get; set; }
        public Nullable<double> ComMvt { get; set; }
        public Nullable<double> ComDec { get; set; }
        public Nullable<double> FTC { get; set; }
        public Nullable<double> TVA { get; set; }
        public Nullable<double> TPRCM { get; set; }
        public string Denomination { get; set; }
        public string CpteCol { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string devise { get; set; }
        public string journal { get; set; }
        public System.DateTime DateOperation { get; set; }
        public decimal Series { get; set; }
        public Nullable<System.DateTime> DateCptab { get; set; }
        public string IntReserved { get; set; }
        public string TxnNo { get; set; }
        public Nullable<double> SMSAmount { get; set; }
        public Nullable<double> SMSVATAmount { get; set; }
        public string Employe { get; set; }
    }
}
