//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal
    {
        public string jnlcode { get; set; }
        public string jnllib { get; set; }
        public Nullable<System.DateTime> jnldat { get; set; }
        public Nullable<short> jnalauto { get; set; }
    }
}
