//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalOperation
    {
        public string NumeroContrat { get; set; }
        public System.DateTime DateOperation { get; set; }
        public string Cptejumellecredit { get; set; }
        public string Denomination { get; set; }
        public Nullable<double> OperationCharge { get; set; }
        public string casereference { get; set; }
        public string Lawyer { get; set; }
        public string InstanceType { get; set; }
        public string Jurisdictiontype { get; set; }
        public string Sentence1 { get; set; }
        public string Sentence2 { get; set; }
        public string Remark1 { get; set; }
        public Nullable<int> employe { get; set; }
        public string libemploye { get; set; }
        public int Serie { get; set; }
    }
}
