//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Litigation
    {
        public int Agence { get; set; }
        public string Numerocontrat { get; set; }
        public string Cptejumellecc { get; set; }
        public string CptejumelleCredit { get; set; }
        public string Denomination { get; set; }
        public string Blocage { get; set; }
        public Nullable<System.DateTime> SuspensionDate { get; set; }
        public Nullable<double> Montant { get; set; }
        public string LibAgence { get; set; }
        public Nullable<int> employe { get; set; }
        public string libemploye { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
