//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanPortfolioClassification
    {
        public string ClassificationCode { get; set; }
        public string ClassificationLibelle { get; set; }
        public Nullable<int> DayBeginClassification { get; set; }
        public Nullable<int> DayEndClassification { get; set; }
        public string DescClassificationPeriode { get; set; }
        public string OptionDay { get; set; }
    }
}
