//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public decimal LogId { get; set; }
        public string UserId { get; set; }
        public string Machine { get; set; }
        public Nullable<System.DateTime> DateOperation { get; set; }
        public string Hour { get; set; }
        public string Action { get; set; }
        public string Message { get; set; }
        public string PSName { get; set; }
        public Nullable<System.DateTime> ServerDate { get; set; }
    }
}
