//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageCashier
    {
        public string Agence { get; set; }
        public string Caisse { get; set; }
        public string CaisseDest { get; set; }
        public string TypeOp { get; set; }
        public Nullable<double> Amount { get; set; }
        public string TellerEmp { get; set; }
        public string ChiefTellerEmp { get; set; }
        public Nullable<System.DateTime> DateOperation { get; set; }
        public string Status { get; set; }
        public Nullable<int> Validation { get; set; }
        public string Validatedby { get; set; }
        public string Series { get; set; }
        public string trftype { get; set; }
        public string AgenceDest { get; set; }
    }
}
