//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class MouchSec
    {
        public Nullable<System.DateTime> datemouch { get; set; }
        public string CreationTime { get; set; }
        public string TaskCode { get; set; }
        public string TaskDescription { get; set; }
        public string Computername { get; set; }
        public string ancienneVal { get; set; }
        public string NouvelleVal { get; set; }
        public string TableMouch { get; set; }
        public string Employe { get; set; }
        public string LibEmploye { get; set; }
        public int Series { get; set; }
        public string Agence { get; set; }
    }
}
