//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mouchard
    {
        public Nullable<short> Agence { get; set; }
        public string TableMouch { get; set; }
        public string Champ { get; set; }
        public string ancienneVal { get; set; }
        public string NouvelleVal { get; set; }
        public Nullable<short> Employe { get; set; }
        public string LibEmploye { get; set; }
        public string LibTable { get; set; }
        public string LibChamp { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> datemouch { get; set; }
        public int Series { get; set; }
    }
}
