//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoucheSup
    {
        public string Agence { get; set; }
        public string TableSup { get; set; }
        public string InfoSup { get; set; }
        public string Employe { get; set; }
        public string LibEmploye { get; set; }
        public string LibTable { get; set; }
        public Nullable<System.DateTime> DateSup { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public int Series { get; set; }
        public string computername { get; set; }
    }
}
