//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class nomenposteOLD
    {
        public string CodePoste { get; set; }
        public string LibPoste { get; set; }
        public string groupcode { get; set; }
        public string groupcodename { get; set; }
        public string etat { get; set; }
        public string libelleetat { get; set; }
        public string CatGroup { get; set; }
        public decimal seriee { get; set; }
        public string Formulas { get; set; }
    }
}
