//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpDiversA
    {
        public string Agence { get; set; }
        public string Client { get; set; }
        public Nullable<short> CatCpte { get; set; }
        public string Subcpte { get; set; }
        public string LetCle { get; set; }
        public string CpteJumelle { get; set; }
        public string Denomination { get; set; }
        public string Devise { get; set; }
        public Nullable<System.DateTime> DateOperation { get; set; }
        public Nullable<System.DateTime> DateValeur { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public string CodeLibelle { get; set; }
        public string LibLibelle { get; set; }
        public string RefOperation { get; set; }
        public string Employe { get; set; }
        public string LibEmploye { get; set; }
        public Nullable<double> TxIntDb { get; set; }
        public Nullable<double> TxIntCr { get; set; }
        public string Description { get; set; }
        public string LibAgence { get; set; }
        public string Journal { get; set; }
        public string LibJournal { get; set; }
        public string CleCol { get; set; }
        public string LibCpteCol { get; set; }
        public string LibDevise { get; set; }
        public string CodeMaj { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string CpteCol { get; set; }
        public string CleColClt { get; set; }
        public string LibCptColClt { get; set; }
        public string CpteColClt { get; set; }
        public string TxnNo { get; set; }
        public string Trcode { get; set; }
        public string cptejumelleproduit { get; set; }
        public Nullable<System.DateTime> DateTransfert { get; set; }
        public decimal Serie { get; set; }
        public string representative { get; set; }
    }
}
