//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutGoingSM
    {
        public decimal outgoingsmsid { get; set; }
        public string customer { get; set; }
        public Nullable<System.DateTime> dateoperation { get; set; }
        public string SMSTransText { get; set; }
        public string CustPhone { get; set; }
        public string Flag { get; set; }
    }
}
