//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametre
    {
        public string CodePara { get; set; }
        public string Libelle { get; set; }
        public string CpteGL { get; set; }
        public Nullable<double> Taux { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<double> Plafond { get; set; }
        public Nullable<double> Plancher { get; set; }
        public string Devise { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Employe { get; set; }
    }
}
