//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlageCustProdStat
    {
        public decimal IDLimit { get; set; }
        public Nullable<double> lowerlimit { get; set; }
        public Nullable<double> UpperLimit { get; set; }
    }
}
