//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlageBilling
    {
        public string CodeOp { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public string CatClient { get; set; }
        public Nullable<double> lowerlimit { get; set; }
        public Nullable<double> UpperLimit { get; set; }
        public Nullable<double> ComHorsTaxe { get; set; }
        public string FlagAmountRate { get; set; }
        public decimal ComID { get; set; }
        public string customerType { get; set; }
    }
}
