//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorteFeuilleLocal
    {
        public string Agence { get; set; }
        public string Client { get; set; }
        public string Denomination { get; set; }
        public string CpteJumelleCC { get; set; }
        public Nullable<short> CatCpte { get; set; }
        public string LetCle { get; set; }
        public string ChequeEffet { get; set; }
        public string EncEscpte { get; set; }
        public Nullable<System.DateTime> DateDepot { get; set; }
        public Nullable<System.DateTime> DateEcheance { get; set; }
        public string Tireur { get; set; }
        public string Domiciliation { get; set; }
        public string Reference { get; set; }
        public string RefInterne { get; set; }
        public string Devise { get; set; }
        public Nullable<double> CoursDevise { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<double> MtEncaisse { get; set; }
        public Nullable<double> FraisCorresp { get; set; }
        public string FraisChargeBenefTir { get; set; }
        public Nullable<double> TauxEscpte { get; set; }
        public Nullable<short> NbreJours { get; set; }
        public Nullable<double> MtInteret { get; set; }
        public string CodeReescompte { get; set; }
        public string SituationValeur { get; set; }
        public string LiaisonCorresp { get; set; }
        public string CodeLiaisonCorresp { get; set; }
        public string CpteLiaisonCorresp { get; set; }
        public Nullable<double> Commission { get; set; }
        public Nullable<double> Taxes { get; set; }
        public string Description { get; set; }
        public string CpteIndEnc { get; set; }
        public string CpteIndEscpteChq { get; set; }
        public string CpteIndEscpteEffet { get; set; }
        public string CpteIndEncEffEscp { get; set; }
        public string CpteIndImpEscpte { get; set; }
        public Nullable<System.DateTime> DateCalcul { get; set; }
        public string ZoneCalcul { get; set; }
        public string SitAnterieurValeur { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> DateCptaEnvoi { get; set; }
        public Nullable<System.DateTime> DateCptaResult { get; set; }
        public string LibLiaisonCorresp { get; set; }
        public string CodeCorrBnk { get; set; }
        public string LibCorrBnk { get; set; }
        public int SerieNum { get; set; }
        public string Employe { get; set; }
        public string LibEmploye { get; set; }
        public Nullable<double> PDL { get; set; }
        public string LibAgence { get; set; }
        public string Tracer { get; set; }
        public Nullable<System.DateTime> DateCptaReception { get; set; }
        public Nullable<double> Unpaidcheckpenalty { get; set; }
        public Nullable<double> OurUnPaidCharge { get; set; }
        public string TxnNo { get; set; }
        public string coltype { get; set; }
    }
}
