//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreprocesInformation
    {
        public int PreprocessId { get; set; }
        public string PrepocessName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PrepocessDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Employe { get; set; }
        public string LibEmploye { get; set; }
        public string PnlStatus { get; set; }
        public string ProcessStatus { get; set; }
        public string ProcessBranch { get; set; }
        public string ComputerName { get; set; }
        public Nullable<decimal> NumberRecord { get; set; }
        public Nullable<double> TotalDebit { get; set; }
        public Nullable<double> TotalCredit { get; set; }
    }
}
