//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CpteClts = new HashSet<CpteClt>();
            this.ProductAttributes = new HashSet<ProductAttribute>();
        }
    
        public int ProductCode { get; set; }
        public string LibProduct { get; set; }
        public string ProductType { get; set; }
        public string LoanType { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Employe { get; set; }
        public string NomEmploye { get; set; }
        public Nullable<System.DateTime> DateTransfert { get; set; }
        public string Opdiver { get; set; }
        public string visibCredit { get; set; }
        public string visdep { get; set; }
        public string VisRet { get; set; }
        public string vispersocheck { get; set; }
        public string viscracc { get; set; }
        public string calint { get; set; }
        public string Fraisexceptype { get; set; }
        public string Blockdatetype { get; set; }
        public string caldatevaltype { get; set; }
        public string decouvert { get; set; }
        public string abonementsms { get; set; }
        public string Acceptdbbal { get; set; }
        public string ApplyStopInt { get; set; }
        public string DirectGLPost { get; set; }
        public string ApplyDormantStatus { get; set; }
        public string ApplyStopPayment { get; set; }
        public string ValidateTransactions { get; set; }
        public string ApplyReservedInterest { get; set; }
        public string AbonnementEbanking { get; set; }
        public Nullable<int> Duration { get; set; }
        public string OrdinaryWithdrawChg { get; set; }
        public string SaturdayWithdrawChg { get; set; }
        public string TPartyWithdrawChg { get; set; }
        public string CounterChequeCharge { get; set; }
        public string ChequeCharges { get; set; }
        public string DepositCharge { get; set; }
        public string ExceedNoTrns { get; set; }
        public string ExceedMaxAmount { get; set; }
        public Nullable<double> MaxNumTrnsPerMonth { get; set; }
        public Nullable<double> MaxAmntTrnsPerMonth { get; set; }
        public Nullable<double> TvaRate { get; set; }
        public string FraisExceptionnel { get; set; }
        public string ODFormFee { get; set; }
        public string dbintpostmeth { get; set; }
        public string LoanTransit { get; set; }
        public string MemberProduct { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CpteClt> CpteClts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAttribute> ProductAttributes { get; set; }
    }
}
