//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFITABILITYGROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROFITABILITYGROUP()
        {
            this.PROFITABILITYTYPEs = new HashSet<PROFITABILITYTYPE>();
        }
    
        public string PROFGROUPNAME { get; set; }
        public string PROFITYPE { get; set; }
        public string PROFDESCGROUP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROFITABILITYTYPE> PROFITABILITYTYPEs { get; set; }
    }
}
