//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfitabilityM
    {
        public Nullable<double> sdebit { get; set; }
        public Nullable<double> scredit { get; set; }
        public Nullable<double> Pmargin { get; set; }
        public string CpteJumelle { get; set; }
        public string Denomination { get; set; }
    }
}
