//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvTrCodeAn
    {
        public string Agence { get; set; }
        public string Journal { get; set; }
        public int Serie { get; set; }
        public string CpteJumelle { get; set; }
        public Nullable<System.DateTime> DateOperation { get; set; }
        public Nullable<double> Montant { get; set; }
        public string Sensimput { get; set; }
        public string Employe { get; set; }
        public string LibAgence { get; set; }
        public string LibJournal { get; set; }
        public string CpteCol { get; set; }
        public string CleCol { get; set; }
        public string LibCpteCol { get; set; }
        public string CodeMaj { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<double> MtCommis { get; set; }
        public string NomEmploye { get; set; }
        public string TxnNo { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> Datevaleur { get; set; }
        public string denomination { get; set; }
        public string codepara { get; set; }
    }
}
