//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class RembAnticipe
    {
        public string Agence { get; set; }
        public int Serie { get; set; }
        public string Client { get; set; }
        public string Denomination { get; set; }
        public string CpteJumelleCC { get; set; }
        public string CpteJumelleCredit { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<System.DateTime> DateOrdre { get; set; }
        public Nullable<double> RembCapital { get; set; }
        public Nullable<double> MtInteret { get; set; }
        public Nullable<double> MtTVA { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> DateCpta { get; set; }
        public string LibAgence { get; set; }
        public string NumeroContrat { get; set; }
        public string txnno { get; set; }
        public Nullable<double> antife { get; set; }
        public Nullable<double> VFDiff { get; set; }
    }
}
