//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemDoc
    {
        public Nullable<short> Agence { get; set; }
        public int Serie { get; set; }
        public Nullable<int> Client { get; set; }
        public string Denomination { get; set; }
        public string CpteJumelleCC { get; set; }
        public Nullable<short> CatCpte { get; set; }
        public string LettreCle { get; set; }
        public string CompteJumelleRemdoc { get; set; }
        public Nullable<System.DateTime> DateOuverture { get; set; }
        public string TypeRemDoc { get; set; }
        public string NatureRemDoc { get; set; }
        public string TypeConfirmation { get; set; }
        public string TypeDocument { get; set; }
        public string Devise { get; set; }
        public string LibDevise { get; set; }
        public string NumRemDoc { get; set; }
        public string Beneficiaire { get; set; }
        public string DomiciliationBenef { get; set; }
        public string AdresseBenef { get; set; }
        public string NatureTransport { get; set; }
        public string OrigineMarchandise { get; set; }
        public string PaysBenef { get; set; }
        public string LibOrigineMarchandise { get; set; }
        public string LibPaysBenef { get; set; }
        public string CpteGL { get; set; }
        public string CleCpte { get; set; }
        public string LibCpteGl { get; set; }
        public Nullable<double> MontantMarchandise { get; set; }
        public Nullable<double> Cours { get; set; }
        public Nullable<double> Commissions { get; set; }
        public Nullable<double> MtTVA { get; set; }
        public Nullable<double> Provision { get; set; }
        public Nullable<double> CoursProvision { get; set; }
        public string Correspondant { get; set; }
        public string LibCorrespondant { get; set; }
        public string CodeTraitImport { get; set; }
        public Nullable<System.DateTime> Validite { get; set; }
        public Nullable<System.DateTime> Embarquement { get; set; }
        public string CodeTraitExport { get; set; }
        public Nullable<System.DateTime> DateCptaOuverture { get; set; }
        public Nullable<System.DateTime> DateCptaRemise { get; set; }
        public Nullable<System.DateTime> DateCptaReceptionExp { get; set; }
        public Nullable<System.DateTime> DateCptaNotifConfExp { get; set; }
        public Nullable<System.DateTime> DateCptaProvision { get; set; }
        public string Statut { get; set; }
        public string TermImp { get; set; }
        public string CpteGLCorresp { get; set; }
        public string CleCpteCorresp { get; set; }
        public string LibCpteGlCorresp { get; set; }
        public string LibAgence { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateEcheance { get; set; }
        public Nullable<System.DateTime> DateCptaConfirmation { get; set; }
        public Nullable<double> FraisAcceptation { get; set; }
        public string CodeEscompte { get; set; }
        public Nullable<double> TauxEscompte { get; set; }
        public Nullable<short> NbreJours { get; set; }
        public Nullable<double> FraisCorresp { get; set; }
        public string CodeBnk { get; set; }
        public string Guichet { get; set; }
        public string CompteBnk { get; set; }
        public string CleCompteBnk { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<double> TVAFCorresp { get; set; }
        public Nullable<System.DateTime> DateCptaTVAFC { get; set; }
    }
}
