//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class REserveAcctInfo
    {
        public string Agence { get; set; }
        public string Cptejumelle { get; set; }
        public string CptejumelleCash { get; set; }
        public Nullable<double> ReserveAmnt { get; set; }
        public string status { get; set; }
        public string StatusClose { get; set; }
        public string StatusPaid { get; set; }
        public string Denomination { get; set; }
        public Nullable<System.DateTime> DateClose { get; set; }
        public Nullable<System.DateTime> DateOpen { get; set; }
        public string LIBCLIENT { get; set; }
    }
}
