//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalTemp
    {
        public string Institution { get; set; }
        public string MatriSalaire { get; set; }
        public string NomFonctionnaire { get; set; }
        public string PrenomFonctionnaire { get; set; }
        public Nullable<double> MontSalaire { get; set; }
        public string CpteJumelle { get; set; }
        public string DateSalaire { get; set; }
        public string Opt1 { get; set; }
        public int Series { get; set; }
    }
}
