//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopPayment
    {
        public string CpteJumelle { get; set; }
        public string TypeValeur { get; set; }
        public string NumChequier { get; set; }
        public Nullable<double> Montant { get; set; }
        public string Beneficiaire { get; set; }
        public Nullable<System.DateTime> DateEmission { get; set; }
        public string Description { get; set; }
        public string Denomination { get; set; }
        public string Agence { get; set; }
        public string LibAgence { get; set; }
        public Nullable<System.DateTime> DateOpposition { get; set; }
        public string Employe { get; set; }
        public string LibEmploye { get; set; }
        public string ValSaisie { get; set; }
        public Nullable<System.DateTime> DateLeveeOpposition { get; set; }
        public Nullable<System.DateTime> Datetransfert { get; set; }
        public string Reference { get; set; }
    }
}
