//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabBudgetAllocated
    {
        public string BudgetID { get; set; }
        public string Agence { get; set; }
        public string DirectorateID { get; set; }
        public string CodeCentre { get; set; }
        public Nullable<double> AllocatedAmount { get; set; }
        public Nullable<double> SpendAmount { get; set; }
        public Nullable<double> LeftAmount { get; set; }
        public int FiscalID { get; set; }
        public string TypeBudget { get; set; }
    
        public virtual tabCostCentre tabCostCentre { get; set; }
        public virtual tabDirectorate tabDirectorate { get; set; }
    }
}
