//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabbilanconfig
    {
        public string ReportHeader { get; set; }
        public string Etat { get; set; }
        public string LibelleEtat { get; set; }
        public string CodePoste { get; set; }
        public string LibPoste { get; set; }
        public string groupcode { get; set; }
        public string groupcodename { get; set; }
        public string CatGroup { get; set; }
        public string CpteGl { get; set; }
        public string TypeCpte { get; set; }
        public string SensInfo { get; set; }
        public string GlPosit { get; set; }
        public string ExclusionAcct { get; set; }
        public string ExcludePosit { get; set; }
        public string cpteamortprov { get; set; }
        public string provdepposit { get; set; }
        public string ExclusionAcct2 { get; set; }
        public string ExclusionAcct3 { get; set; }
        public string ExclusionAcct4 { get; set; }
        public string ExclusionAcct5 { get; set; }
        public string ExclusionAcct6 { get; set; }
        public string ExclusionAcct7 { get; set; }
        public string ExclusionAcct8 { get; set; }
        public string cpteamortprov2 { get; set; }
        public string cpteamortprov3 { get; set; }
        public string cpteamortprov4 { get; set; }
        public string cpteamortexc1 { get; set; }
        public string cpteamortexc2 { get; set; }
        public string cpteamortexc3 { get; set; }
        public string cpteamortexc4 { get; set; }
        public string lignecode { get; set; }
        public string grouping { get; set; }
    }
}
