//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabCashOptn
    {
        public int CTrnCode { get; set; }
        public double OptnAmount { get; set; }
        public double ComAmount { get; set; }
        public double PayAmount { get; set; }
        public double TaxAmount { get; set; }
        public string Description { get; set; }
        public System.DateTime TrnDate { get; set; }
        public string CashTrCodeName { get; set; }
        public string CashTrCode { get; set; }
        public string SensImput { get; set; }
        public string TrCode { get; set; }
        public string Reference { get; set; }
        public string CpteGlCom { get; set; }
        public string CleCpteCom { get; set; }
        public string LibCpteGLCom { get; set; }
        public string CpteGl { get; set; }
        public string CleCpte { get; set; }
        public string LibCpteGL { get; set; }
        public string Employe { get; set; }
        public string LibEmploye { get; set; }
        public Nullable<System.DateTime> datecpta { get; set; }
        public string Cptejumelle { get; set; }
        public string Denomination { get; set; }
        public string trftype { get; set; }
        public string CptecltBenef { get; set; }
        public string custnameben { get; set; }
        public string StatusOperation { get; set; }
        public string SenderName { get; set; }
        public string ReceiverName { get; set; }
        public string Validation { get; set; }
        public string Authoriser { get; set; }
        public Nullable<System.DateTime> datecptapayment { get; set; }
        public string employepayment { get; set; }
        public string agenceemt { get; set; }
        public string agencedest { get; set; }
        public string agencepay { get; set; }
        public Nullable<int> statut { get; set; }
    }
}
