//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabcoefliquidite
    {
        public string ReportHeader { get; set; }
        public string Etat { get; set; }
        public string LibelleEtat { get; set; }
        public string CodePoste { get; set; }
        public string LibPoste { get; set; }
        public string groupcode { get; set; }
        public string groupcodename { get; set; }
        public string CatGroup { get; set; }
        public string CpteGl { get; set; }
        public string GlPosit { get; set; }
        public string TypeCpte { get; set; }
        public string SensInfo { get; set; }
    }
}
