//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabCpteMembretmp
    {
        public string Client { get; set; }
        public string CpteJumelle { get; set; }
        public string LibCatCpte { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<double> balanceBlock { get; set; }
        public Nullable<double> Netbalance { get; set; }
        public string Employe { get; set; }
    }
}
