//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabCashOptnsSm
    {
        public int CTrnCode { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public double OptnAmount { get; set; }
        public double ComAmount { get; set; }
        public double PayAmount { get; set; }
        public double TaxAmount { get; set; }
        public System.DateTime TrnDate { get; set; }
        public string CashTrCodeName { get; set; }
        public string CashTrCode { get; set; }
        public string SensImput { get; set; }
        public string TrCode { get; set; }
        public string CpteGlCom { get; set; }
        public string CleCpteCom { get; set; }
        public string LibCpteGLCom { get; set; }
        public string CpteGl { get; set; }
        public string CleCpte { get; set; }
        public string LibCpteGL { get; set; }
        public Nullable<int> Employe { get; set; }
        public string LibEmploye { get; set; }
        public Nullable<System.DateTime> datecpta { get; set; }
        public string Cptejumelle { get; set; }
        public string Denomination { get; set; }
        public string CptejumelleDonOrdre { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
