//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabCreditError
    {
        public Nullable<int> Agence { get; set; }
        public Nullable<int> Client { get; set; }
        public string CpteJumelleCC { get; set; }
        public string CpteJumellecredit { get; set; }
        public string Denomination { get; set; }
        public Nullable<double> TotalRembCapital { get; set; }
        public Nullable<double> TotalARembCapital { get; set; }
        public Nullable<double> RunningCap { get; set; }
        public Nullable<double> SoldeHisto { get; set; }
    }
}
