//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabCashTrancode
    {
        public string CashTrCode { get; set; }
        public string TrCode { get; set; }
        public string LibTrCode { get; set; }
        public string CpteGL { get; set; }
        public string CleCpte { get; set; }
        public string LibCpteGl { get; set; }
        public string SensImput { get; set; }
        public Nullable<short> Employe { get; set; }
        public string nomEmploye { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public int SerieNum { get; set; }
        public string CashTrCodeName { get; set; }
        public string newoption { get; set; }
        public Nullable<decimal> optncounter { get; set; }
        public string BranchCode { get; set; }
    }
}
