//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabDirectorate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabDirectorate()
        {
            this.tabBudgetAllocateds = new HashSet<tabBudgetAllocated>();
        }
    
        public string DirectorateCode { get; set; }
        public string DirectorateName { get; set; }
        public string DirectorateHead { get; set; }
        public string ContactNumber { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> FiscalID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabBudgetAllocated> tabBudgetAllocateds { get; set; }
        public virtual tabFiscalMaster tabFiscalMaster { get; set; }
    }
}
