//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabEmpSalary
    {
        public int Agence { get; set; }
        public string CpteJumelle { get; set; }
        public string Denomination { get; set; }
        public Nullable<double> MontantSal { get; set; }
        public Nullable<System.DateTime> DatePaie { get; set; }
        public string TxnNo { get; set; }
    }
}
