//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabExemptBudget
    {
        public string CodeCentre { get; set; }
        public string CentreName { get; set; }
        public string CpteGL { get; set; }
        public string LibCpteGl { get; set; }
        public string CleCpte { get; set; }
    }
}
