//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabErrorModifSize
    {
        public decimal pk { get; set; }
        public string TableName { get; set; }
        public string ColumName { get; set; }
        public string Motif { get; set; }
    }
}
