//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabFBAuxBal
    {
        public decimal pk { get; set; }
        public Nullable<int> Agence { get; set; }
        public Nullable<System.DateTime> DateOperation { get; set; }
        public string compte { get; set; }
        public Nullable<double> DBClt { get; set; }
        public Nullable<double> CRClt { get; set; }
        public Nullable<double> Soldeclt { get; set; }
        public Nullable<double> DBGl { get; set; }
        public Nullable<double> CRGl { get; set; }
        public Nullable<double> SoldeGL { get; set; }
        public Nullable<double> diferrence { get; set; }
    }
}
