//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabFiscalMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabFiscalMaster()
        {
            this.tabDirectorates = new HashSet<tabDirectorate>();
        }
    
        public int FiscalID { get; set; }
        public Nullable<System.DateTime> StartingFrom { get; set; }
        public Nullable<System.DateTime> EndFrom { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string BudGetID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabDirectorate> tabDirectorates { get; set; }
    }
}
