//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabJnlPartMember
    {
        public string Agence { get; set; }
        public string LibAgence { get; set; }
        public string Client { get; set; }
        public Nullable<int> CatCpte { get; set; }
        public string CpteJumelle { get; set; }
        public string Denomination { get; set; }
        public string Mois { get; set; }
        public string LibelleMois { get; set; }
        public string YearOp { get; set; }
        public Nullable<double> MntPart { get; set; }
        public Nullable<double> SoldeSavingAcc { get; set; }
        public Nullable<double> SoldeShareAcct { get; set; }
        public string devise { get; set; }
        public Nullable<System.DateTime> DateOperation { get; set; }
        public Nullable<System.DateTime> DateCptabProv { get; set; }
        public string TxnNo { get; set; }
        public decimal Series { get; set; }
        public string Employe { get; set; }
        public Nullable<double> EstRate { get; set; }
        public Nullable<double> IntProv { get; set; }
        public Nullable<System.DateTime> DateCptab { get; set; }
    }
}
