//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Archive
    {
        public System.DateTime ArchiveDate { get; set; }
        public string Employe { get; set; }
        public string Libemploye { get; set; }
        public string Agence { get; set; }
    }
}
