//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABMEMBERBENEF
    {
        public decimal PK { get; set; }
        public string Nombenef { get; set; }
        public string Cni { get; set; }
        public string rel { get; set; }
        public Nullable<int> ratio { get; set; }
        public string CLIENT { get; set; }
    
        public virtual ClientBnk ClientBnk { get; set; }
    }
}
