//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabreportOLD
    {
        public string etat { get; set; }
        public string libelleetat { get; set; }
        public string periodicite { get; set; }
        public decimal idReport { get; set; }
    }
}
