//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabSundryTransaction
    {
        public decimal STID { get; set; }
        public string CodeCentre { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> FiscalID { get; set; }
        public string SensImputation { get; set; }
        public string BudgetID { get; set; }
        public string DirectorateID { get; set; }
        public string Agence { get; set; }
    }
}
