//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabtreasuryconsult
    {
        public string CodeCaisse { get; set; }
        public string Compte { get; set; }
        public Nullable<double> MontantDep { get; set; }
        public Nullable<double> DebitJour { get; set; }
        public Nullable<double> CreditJour { get; set; }
        public Nullable<double> Solde { get; set; }
        public Nullable<double> MtCorresp { get; set; }
        public string Devise { get; set; }
        public string LibCompte { get; set; }
        public Nullable<int> agence { get; set; }
        public string libagence { get; set; }
    }
}
