//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMPCustLoanClassification
    {
        public string AGENCE { get; set; }
        public string CPTEJUMELLE { get; set; }
        public string DENOMMINATION { get; set; }
        public string CONTRACTNUMBER { get; set; }
        public string CUSTOMERTYPE { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<int> NBDAYS { get; set; }
        public string RANGE { get; set; }
        public string CODERANGE { get; set; }
        public string LIBELLERANGE { get; set; }
        public string EMPLOYE { get; set; }
        public Nullable<double> SAVINGS { get; set; }
        public string LIBAGENCE { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
    }
}
