//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpDAteRange
    {
        public System.DateTime datefin { get; set; }
        public System.DateTime datedebut { get; set; }
        public string selectioncriteria { get; set; }
        public string fieldvalue { get; set; }
        public string groupby { get; set; }
    }
}
