//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpDormantToClose
    {
        public int Agence { get; set; }
        public decimal Client { get; set; }
        public string CpteJumelle { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public string LibClient { get; set; }
        public string LetCle { get; set; }
        public string Statut { get; set; }
        public string LibAgence { get; set; }
        public int Employe { get; set; }
        public string Nomemploye { get; set; }
        public string dormantstatus { get; set; }
    }
}
