//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpProfitability
    {
        public string Agence { get; set; }
        public string LibAgence { get; set; }
        public string Matricule { get; set; }
        public string CpteJumelle { get; set; }
        public string Denomination { get; set; }
        public string GroupName { get; set; }
        public string GroupDesc { get; set; }
        public string ProfitName { get; set; }
        public string ProfitDesc { get; set; }
        public string Type { get; set; }
        public Nullable<double> Valeur { get; set; }
        public decimal Pk { get; set; }
    }
}
