//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpStatementIncExp
    {
        public int Matricule { get; set; }
        public string Account { get; set; }
        public Nullable<double> Branch1 { get; set; }
        public Nullable<double> Branch2 { get; set; }
        public Nullable<double> Branch3 { get; set; }
        public Nullable<double> Branch4 { get; set; }
        public Nullable<double> Branch5 { get; set; }
        public Nullable<double> Branch6 { get; set; }
        public Nullable<double> Branch7 { get; set; }
        public Nullable<double> Branch8 { get; set; }
        public Nullable<double> Branch9 { get; set; }
        public Nullable<double> Branch10 { get; set; }
        public Nullable<double> Branch11 { get; set; }
        public Nullable<double> Branch12 { get; set; }
        public Nullable<double> Branch13 { get; set; }
    }
}
