//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMPSM
    {
        public string AGENCE { get; set; }
        public string CLIENT { get; set; }
        public string DENOMMINATION { get; set; }
        public string CONTRACTNUMBER { get; set; }
        public Nullable<System.DateTime> DATECREDIT { get; set; }
        public Nullable<System.DateTime> LASTREPDATE { get; set; }
        public string EMPLOYE { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<double> NBJOUR { get; set; }
        public string VAL { get; set; }
        public decimal SERIE { get; set; }
    }
}
