//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trancode
    {
        public string TrCode { get; set; }
        public string Designation { get; set; }
        public string CodePara { get; set; }
        public string SensImput { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Employe { get; set; }
        public string lot { get; set; }
        public Nullable<int> optncounter { get; set; }
        public string codeoperation { get; set; }
        public string libelleoperation { get; set; }
        public string BranchCode { get; set; }
        public string ImputAg { get; set; }
    }
}
