//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferState
    {
        public string Agence { get; set; }
        public string LibAgence { get; set; }
        public int Employe { get; set; }
        public string LibEmploye { get; set; }
        public System.DateTime DateTransfert { get; set; }
        public string TableTranferer { get; set; }
        public string Statut { get; set; }
    }
}
