//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANS_REF
    {
        public string CODEOP { get; set; }
        public Nullable<decimal> MAXCOUNTER { get; set; }
        public Nullable<decimal> COUNTER { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
    }
}
