//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSFERPRODUCT
    {
        public string CPTEJUMELLE { get; set; }
        public string Denomination { get; set; }
        public string CODEAUTOTRF { get; set; }
        public Nullable<double> AMOUNTTRF { get; set; }
        public Nullable<System.DateTime> DatedernierCpta { get; set; }
    }
}
