//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransForce
    {
        public string Denomination { get; set; }
        public Nullable<double> SoldeClt { get; set; }
        public string Sens { get; set; }
        public Nullable<double> OptnAmount { get; set; }
        public string fpval { get; set; }
        public string CpteJumelle { get; set; }
        public string LigneDec { get; set; }
        public string Possible { get; set; }
        public string ForcedBy { get; set; }
        public string SuperPin { get; set; }
        public string OptnType { get; set; }
        public string Status { get; set; }
        public string matricule { get; set; }
        public string requestby { get; set; }
        public string ComputerName { get; set; }
        public Nullable<System.DateTime> dateexp { get; set; }
        public string MotifRejet { get; set; }
        public System.DateTime DateOperation { get; set; }
        public string FStatus { get; set; }
        public decimal Series { get; set; }
        public string RefOperation { get; set; }
        public Nullable<System.DateTime> Datevaleur { get; set; }
        public string Remarks { get; set; }
        public string agence { get; set; }
    }
}
