//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransfExt
    {
        public short Agence { get; set; }
        public int Serie { get; set; }
        public string CpteJumelleCC { get; set; }
        public string Denomination { get; set; }
        public Nullable<System.DateTime> DateOuverture { get; set; }
        public string Typetransfert { get; set; }
        public string Devise { get; set; }
        public string LibDevise { get; set; }
        public string NumOrdreVir { get; set; }
        public string Beneficiaire { get; set; }
        public string DomiciliationBenef { get; set; }
        public string CodeBnkBenef { get; set; }
        public string Guichet { get; set; }
        public string CompteBnk { get; set; }
        public string CleCompteBnk { get; set; }
        public string AdresseBenef { get; set; }
        public string PaysBenef { get; set; }
        public string LibPaysBenef { get; set; }
        public string BanqueReglement { get; set; }
        public string AdBanqueReglement { get; set; }
        public string CodeSWIFT { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<double> Cours { get; set; }
        public Nullable<double> CVCFA { get; set; }
        public string Correspondant { get; set; }
        public string LibCorrespondant { get; set; }
        public string CpteGLCorresp { get; set; }
        public string CleCpteCorresp { get; set; }
        public string LibCpteCorresp { get; set; }
        public string AutDecl { get; set; }
        public Nullable<System.DateTime> DateDecl { get; set; }
        public Nullable<double> MtDeclAut { get; set; }
        public Nullable<short> VPEchPasse { get; set; }
        public string ModeEnvoi { get; set; }
        public Nullable<double> FraisEnvoi { get; set; }
        public Nullable<int> Employe { get; set; }
        public string LibEmploye { get; set; }
        public Nullable<short> NbreAvis { get; set; }
        public string ZoneMonaie { get; set; }
        public string Motif { get; set; }
        public string Description { get; set; }
        public string StatutAvis { get; set; }
        public Nullable<System.DateTime> DateTransf { get; set; }
        public string LibAgence { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
    }
}
