//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trbillinglist
    {
        public string CODEOP { get; set; }
        public string JNLCODE { get; set; }
        public string LibJournal { get; set; }
        public string COMPTE { get; set; }
        public string LibCompte { get; set; }
        public string TRCODE { get; set; }
        public string LibTrCode { get; set; }
        public string CatClient { get; set; }
        public string LibCatClient { get; set; }
        public int ProductCode { get; set; }
        public string LibProduct { get; set; }
        public string TYPEOP { get; set; }
        public string LIBELLEOP { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<double> TAUX { get; set; }
        public string APPLYVAT { get; set; }
        public string FLAGAMTTAUXPLAGE { get; set; }
        public string FLAGPRODATTRIB { get; set; }
        public string MODEOP { get; set; }
        public string SENSOP { get; set; }
        public string PERIODICITE { get; set; }
        public Nullable<decimal> MAXCOUNTER { get; set; }
        public Nullable<decimal> COUNTER { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string PROFGROUPNAME { get; set; }
        public string PROFITABILITYNAME { get; set; }
        public string PROFITDESCRIPTION { get; set; }
        public string PROFITYPE { get; set; }
        public string CustomerType { get; set; }
    }
}
