//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrCodeAnnexe
    {
        public string TrCode { get; set; }
        public string LibTrCode { get; set; }
        public int SerieNum { get; set; }
        public string CodePara { get; set; }
        public string LibPara { get; set; }
        public string SensImput { get; set; }
        public string CpteGl { get; set; }
        public string CleGl { get; set; }
        public string LibCpteGl { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<short> Employe { get; set; }
        public string NomEmploye { get; set; }
    }
}
