//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnionInfo
    {
        public string UnionName { get; set; }
        public Nullable<System.DateTime> EstablsihDate { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string RegistrationNb { get; set; }
        public string Membership { get; set; }
        public string IDData { get; set; }
        public string Chapter { get; set; }
        public string Province { get; set; }
        public string Division { get; set; }
        public string SubDivision { get; set; }
        public string Milieu { get; set; }
        public string PayDeduction { get; set; }
        public string BondType { get; set; }
        public string PCProgram { get; set; }
        public string RMProgram { get; set; }
        public string Unioncode { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> EstablishDate { get; set; }
    }
}
