//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AuditCpteclt
    {
        public string Agence { get; set; }
        public decimal Client { get; set; }
        public string CpteJumelle { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public string LibClient { get; set; }
        public Nullable<short> CatCpte { get; set; }
        public string LibCatCpte { get; set; }
        public Nullable<short> Subcpte { get; set; }
        public string LetCle { get; set; }
        public string Devise { get; set; }
        public Nullable<double> LigneDec { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public string CpteCol { get; set; }
        public string CleCol { get; set; }
        public Nullable<System.DateTime> DateOuverture { get; set; }
        public Nullable<int> Gestionnaire { get; set; }
        public string Statut { get; set; }
        public Nullable<System.DateTime> DateEff { get; set; }
        public Nullable<short> TotalSignature { get; set; }
        public Nullable<short> SignatureVal { get; set; }
        public string Fusion { get; set; }
        public string LibAgence { get; set; }
        public string LibDevise { get; set; }
        public string LibCpteCol { get; set; }
        public string LibGestionnaire { get; set; }
        public string CpteOvation { get; set; }
        public Nullable<double> TxIntDb { get; set; }
        public Nullable<double> TxIntCr { get; set; }
        public string ExoTDC { get; set; }
        public string ExoTVA { get; set; }
        public string ExoTPRCM { get; set; }
        public string ExoFTC { get; set; }
        public Nullable<double> TxComDec { get; set; }
        public Nullable<double> TxComMvt { get; set; }
        public Nullable<double> TxTVA { get; set; }
        public Nullable<int> MtFTC { get; set; }
        public Nullable<int> Employe { get; set; }
        public string Nomemploye { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> Expirationlignedec { get; set; }
        public string CRBlocage { get; set; }
        public string DBBlocage { get; set; }
        public Nullable<double> Cantonnement { get; set; }
        public Nullable<System.DateTime> CRBlockDate { get; set; }
        public Nullable<System.DateTime> DBBlockDate { get; set; }
        public Nullable<System.DateTime> DateDernierMvtDB { get; set; }
        public Nullable<System.DateTime> DateDernierMvtCR { get; set; }
        public Nullable<System.DateTime> StopIntDate { get; set; }
        public string StopInt { get; set; }
        public string ReservedInt { get; set; }
        public string ControlAcces { get; set; }
        public string Signerinfo { get; set; }
        public Nullable<System.DateTime> DateDeclaration { get; set; }
        public string dormantstatus { get; set; }
        public string integritystatus { get; set; }
        public string RowStatus { get; set; }
    }
}
