//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AuditJnalRembLoan
    {
        public string agence { get; set; }
        public string CpteCredit { get; set; }
        public Nullable<int> Serie { get; set; }
        public string CpteCC { get; set; }
        public System.DateTime DateOp { get; set; }
        public double CapitalARemb { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<System.DateTime> DateAccord { get; set; }
        public Nullable<double> RembCapMois { get; set; }
        public Nullable<double> IntMois { get; set; }
        public Nullable<double> TVAMois { get; set; }
        public Nullable<double> RembPerDiff { get; set; }
        public string ZoneMaj { get; set; }
        public Nullable<double> PourcentProv { get; set; }
        public Nullable<System.DateTime> DateTrait { get; set; }
        public Nullable<System.DateTime> DateTrImp { get; set; }
        public Nullable<System.DateTime> DateCpta { get; set; }
        public Nullable<System.DateTime> DateCptaAccord { get; set; }
        public Nullable<System.DateTime> DatePassAutre { get; set; }
        public string FPVal { get; set; }
        public string CpteIndAgioRes { get; set; }
        public string CpteJumelleImp { get; set; }
        public string NumeroContrat { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Denomination { get; set; }
        public Nullable<System.DateTime> datetcptafpval { get; set; }
        public Nullable<int> CatCpte { get; set; }
        public string txnno { get; set; }
        public Nullable<System.DateTime> DateTransfert { get; set; }
        public string RowStatus { get; set; }
    }
}
